@tool
extends "res://tests/support/TestSuiteBase.gd"

func suite_name() -> String:
	return "ui_authoring"

func test_ui_scenes_are_editor_authored_for_360_viewport() -> void:
	var app_base_scene := FileAccess.get_file_as_string("res://scenes/ui/AppPanelBase.tscn")
	var app_panel_source := FileAccess.get_file_as_string("res://scripts/ui/AppPanel.gd")
	var main_scene := FileAccess.get_file_as_string("res://scenes/main/Main.tscn")
	var top_scene := FileAccess.get_file_as_string("res://scenes/ui/TopStatusBar.tscn")
	var menu_scene := FileAccess.get_file_as_string("res://scenes/ui/FloatingMenu.tscn")
	var menu_source := FileAccess.get_file_as_string("res://scripts/ui/FloatingMenu.gd")
	var placement_scene := FileAccess.get_file_as_string("res://scenes/ui/PlacementOverlay.tscn")
	var placement_source := FileAccess.get_file_as_string("res://scripts/ui/PlacementOverlay.gd")
	var furniture_controls_scene := FileAccess.get_file_as_string("res://scenes/furniture/FurnitureFloatingControls.tscn")
	var icon_row_scene := FileAccess.get_file_as_string("res://scenes/ui/IconInfoRow.tscn")
	var stat_card_scene := FileAccess.get_file_as_string("res://scenes/ui/StatCard.tscn")
	var progress_card_scene := FileAccess.get_file_as_string("res://scenes/ui/ProgressCard.tscn")
	var progress_card_source := FileAccess.get_file_as_string("res://scripts/ui/ProgressCard.gd")
	var task_item_row_scene := FileAccess.get_file_as_string("res://scenes/ui/TaskItemRow.tscn")
	var task_item_row_source := FileAccess.get_file_as_string("res://scripts/ui/TaskItemRow.gd")
	var furniture_shop_item_row_scene := FileAccess.get_file_as_string("res://scenes/ui/FurnitureShopItemRow.tscn")
	var furniture_shop_item_row_source := FileAccess.get_file_as_string("res://scripts/ui/FurnitureShopItemRow.gd")
	var room_furniture_item_row_scene := FileAccess.get_file_as_string("res://scenes/ui/RoomFurnitureItemRow.tscn")
	var room_furniture_item_row_source := FileAccess.get_file_as_string("res://scripts/ui/RoomFurnitureItemRow.gd")
	var rent_room_row_scene := FileAccess.get_file_as_string("res://scenes/ui/RentRoomRow.tscn")
	var rent_room_row_source := FileAccess.get_file_as_string("res://scripts/ui/RentRoomRow.gd")
	var floor_overview_row_scene := FileAccess.get_file_as_string("res://scenes/ui/FloorOverviewRow.tscn")
	var floor_overview_row_source := FileAccess.get_file_as_string("res://scripts/ui/FloorOverviewRow.gd")
	var tenant_overview_row_scene := FileAccess.get_file_as_string("res://scenes/ui/TenantOverviewRow.tscn")
	var tenant_overview_row_source := FileAccess.get_file_as_string("res://scripts/ui/TenantOverviewRow.gd")
	var tab_button_scene := FileAccess.get_file_as_string("res://scenes/ui/PanelTabButton.tscn")
	var tab_button_source := FileAccess.get_file_as_string("res://scripts/ui/PanelTabButton.gd")
	var action_button_scene := FileAccess.get_file_as_string("res://scenes/ui/PanelActionButton.tscn")
	var action_button_source := FileAccess.get_file_as_string("res://scripts/ui/PanelActionButton.gd")
	var room_panel_scene := FileAccess.get_file_as_string("res://scenes/ui/RoomPanel.tscn")
	var room_panel_source := FileAccess.get_file_as_string("res://scripts/ui/RoomPanel.gd")
	var shop_panel_scene := FileAccess.get_file_as_string("res://scenes/ui/FurnitureShopPanel.tscn")
	var shop_panel_source := FileAccess.get_file_as_string("res://scripts/ui/FurnitureShopPanel.gd")
	var tenant_panel_scene := FileAccess.get_file_as_string("res://scenes/ui/TenantPanel.tscn")
	var tenant_panel_source := FileAccess.get_file_as_string("res://scripts/ui/TenantPanel.gd")
	var overview_panel_scene := FileAccess.get_file_as_string("res://scenes/ui/ApartmentOverviewPanel.tscn")
	var overview_panel_source := FileAccess.get_file_as_string("res://scripts/ui/ApartmentOverviewPanel.gd")
	var build_panel_scene := FileAccess.get_file_as_string("res://scenes/ui/BuildConfirmPopup.tscn")
	var build_panel_source := FileAccess.get_file_as_string("res://scripts/ui/BuildConfirmPopup.gd")
	var income_panel_scene := FileAccess.get_file_as_string("res://scenes/ui/IncomeDetailPanel.tscn")
	var income_panel_source := FileAccess.get_file_as_string("res://scripts/ui/IncomeDetailPanel.gd")
	var rent_panel_scene := FileAccess.get_file_as_string("res://scenes/ui/RentDetailPanel.tscn")
	var rent_panel_source := FileAccess.get_file_as_string("res://scripts/ui/RentDetailPanel.gd")
	var recycle_panel_scene := FileAccess.get_file_as_string("res://scenes/ui/RecycleConfirmPopup.tscn")
	var recycle_panel_source := FileAccess.get_file_as_string("res://scripts/ui/RecycleConfirmPopup.gd")
	var task_panel_scene := FileAccess.get_file_as_string("res://scenes/ui/TaskPanel.tscn")
	var reward_panel_scene := FileAccess.get_file_as_string("res://scenes/ui/RewardPanel.tscn")
	var reward_panel_source := FileAccess.get_file_as_string("res://scripts/ui/RewardPanel.gd")
	var settings_panel_scene := FileAccess.get_file_as_string("res://scenes/ui/SettingsPanel.tscn")
	var settings_panel_source := FileAccess.get_file_as_string("res://scripts/ui/SettingsPanel.gd")
	var offline_panel_scene := FileAccess.get_file_as_string("res://scenes/ui/OfflineRewardPopup.tscn")
	var offline_panel_source := FileAccess.get_file_as_string("res://scripts/ui/OfflineRewardPopup.gd")
	var factory_source := FileAccess.get_file_as_string("res://scripts/ui/UIPanelFactory.gd")
	assert_true(app_base_scene.contains("PanelBox"), "App panels should expose their structure in an editable base scene")
	assert_true(app_base_scene.contains("TitleLabel"), "AppPanelBase should expose the title label")
	assert_true(app_base_scene.contains("CloseButton"), "AppPanelBase should expose the close button")
	assert_true(app_base_scene.contains("ContentRoot"), "AppPanelBase should expose the content container")
	assert_true(app_panel_source.contains("get_node_or_null(\"PanelBox/Header/TitleLabel\")"), "AppPanel should bind editor-authored nodes first")
	assert_true(app_panel_source.contains("func setup_panel(title := \"\", clear_existing := false)"), "AppPanel should preserve editor-authored titles when no runtime title is supplied")
	assert_false(app_panel_source.contains("func use_center_popup"), "Center-popup layout should be authored in each .tscn scene")
	assert_false(app_panel_source.contains("func use_bottom_sheet"), "Bottom-sheet layout should be authored in each .tscn scene")
	assert_false(app_panel_source.contains("set_anchors_preset"), "AppPanel should not set fixed panel anchors in script")
	assert_false(app_panel_source.contains("offset_left"), "AppPanel should not set fixed panel offsets in script")
	for path in _app_panel_scene_paths():
		var scene_source := FileAccess.get_file_as_string(path)
		assert_true(scene_source.contains("res://scenes/ui/AppPanelBase.tscn"), "%s should inherit the editable AppPanelBase scene" % path)
		assert_true(scene_source.contains("custom_minimum_size = Vector2"), "%s should configure its preview size in the scene" % path)
		assert_true(scene_source.contains("anchors_preset = "), "%s should configure its panel anchors in the scene" % path)
	assert_true(top_scene.contains("LevelButton"), "TopStatusBar should expose its level button in the scene")
	assert_true(top_scene.contains("CoinButton"), "TopStatusBar should expose its coin button in the scene")
	assert_true(top_scene.contains("RentButton"), "TopStatusBar should expose its rent button in the scene")
	assert_true(top_scene.contains("custom_minimum_size = Vector2(300, 40)"), "TopStatusBar should be a 300px centered HUD strip")
	assert_eq(top_scene.count("custom_minimum_size = Vector2(96, 0)"), 3, "TopStatusBar value buttons should share the same fixed minimum width")
	assert_true(main_scene.contains("offset_left = -150.0"), "Main should center the 300px TopStatusBar")
	assert_true(main_scene.contains("offset_right = 150.0"), "Main should center the 300px TopStatusBar")
	var rent_button_start := top_scene.find("[node name=\"RentButton\"")
	var rent_button_end := top_scene.find("[node name=\"CoinGainPopup\"", rent_button_start)
	var rent_button_scene := top_scene.substr(rent_button_start, rent_button_end - rent_button_start)
	assert_false(rent_button_scene.contains("\nicon ="), "RentButton should render text only without an icon")
	assert_true(menu_scene.contains("TaskButton"), "FloatingMenu should expose task button in the scene")
	assert_false(menu_scene.contains("ZoomInButton"), "FloatingMenu should remove manual zoom-in button")
	assert_false(menu_scene.contains("ZoomOutButton"), "FloatingMenu should remove manual zoom-out button")
	assert_false(menu_scene.contains("icons/Plus.png"), "FloatingMenu should not keep zoom-in icon resources")
	assert_false(menu_scene.contains("icons/Minus.png"), "FloatingMenu should not keep zoom-out icon resources")
	assert_true(menu_scene.contains("custom_minimum_size = Vector2(46, 0)"), "FloatingMenu should be sized for a 360px viewport")
	assert_false(menu_scene.contains("[node name=\"ZoomTooltipTemplate\" type=\"Label\""), "FloatingMenu should not keep zoom tooltip templates after removing zoom buttons")
	assert_false(menu_source.contains("zoom_in_requested"), "FloatingMenu should not expose removed zoom-in signal")
	assert_false(menu_source.contains("set_zoom_state"), "FloatingMenu should not keep removed zoom button state helpers")
	assert_false(placement_scene.contains("PlacementControls"), "Placement overlay should not keep the old bottom-sheet controls")
	assert_true(placement_scene.contains("HintStrip"), "Placement overlay should expose its lightweight hint strip in the scene")
	assert_true(placement_scene.contains("FloatingControls"), "Placement overlay should expose floating controls in the scene")
	assert_true(placement_scene.contains("res://scenes/furniture/FurnitureFloatingControls.tscn"), "Placement overlay should reuse the furniture floating controls scene")
	assert_true(placement_scene.contains("mouse_filter = 0"), "Placement overlay should capture drag input while placement is active")
	assert_true(placement_source.contains("get_node_or_null(\"HintStrip\")"), "Placement overlay should bind editor-authored hint strip first")
	assert_true(placement_source.contains("get_node_or_null(\"FloatingControls\")"), "Placement overlay should bind editor-authored floating controls first")
	assert_true(placement_source.contains("func _gui_input"), "Placement overlay should receive direct GUI drag events")
	assert_true(placement_scene.contains("[node name=\"TemplateText\" type=\"Control\""), "Placement overlay should keep dynamic text templates as scene nodes")
	assert_true(placement_scene.contains("[node name=\"PlaceConfirmText\" type=\"Label\""), "Placement overlay should keep confirm text as a scene label")
	assert_true(placement_scene.contains("[node name=\"PlaceHintTemplate\" type=\"Label\""), "Placement overlay should keep placement hint copy as a scene label")
	assert_true(placement_scene.contains("[node name=\"MoveHintTemplate\" type=\"Label\""), "Placement overlay should keep move hint copy as a scene label")
	assert_false(placement_source.contains("@export"), "Placement overlay should not require script exports for editor-authored text templates")
	assert_false(placement_source.contains("确认摆放并扣金币"), "Placement overlay should not hard-code confirm copy in script")
	assert_true(furniture_controls_scene.contains("ConfirmButton"), "Furniture floating controls should expose confirm button in the scene")
	assert_true(furniture_controls_scene.contains("CancelButton"), "Furniture floating controls should expose cancel button in the scene")
	assert_true(furniture_controls_scene.contains("RecycleButton"), "Furniture floating controls should expose recycle button in the scene")
	assert_true(furniture_controls_scene.contains("custom_minimum_size = Vector2(40, 38)"), "Furniture floating controls should use compact icon buttons")
	assert_true(furniture_controls_scene.contains("icons/Check.png"), "Furniture floating controls should configure confirm icon in the scene")
	assert_true(furniture_controls_scene.contains("icons/Close.png"), "Furniture floating controls should configure cancel icon in the scene")
	assert_false(furniture_controls_scene.contains("\ntext = \"确认\""), "Furniture floating controls should not use wide text buttons")
	assert_true(icon_row_scene.contains("TitleLabel"), "Repeated icon-info rows should live in a reusable scene")
	assert_true(icon_row_scene.contains("DetailLabel"), "IconInfoRow should expose detail text in the scene")
	assert_true(stat_card_scene.contains("ValueLabel"), "StatCard should expose value text in a reusable scene")
	assert_true(progress_card_scene.contains("ProgressBar"), "ProgressCard should expose its scene-authored progress bar")
	assert_true(progress_card_scene.contains("[node name=\"TitleTemplate\" type=\"Label\""), "ProgressCard should keep title templates as scene labels")
	assert_true(progress_card_scene.contains("[node name=\"FallbackTitle\" type=\"Label\""), "ProgressCard should keep fallback title copy in the scene")
	assert_false(progress_card_source.contains("@export"), "ProgressCard should not require script exports for editor-authored text templates")
	assert_false(progress_card_source.contains("\"Progress\""), "ProgressCard should not keep display fallback copy in script")
	assert_true(task_item_row_scene.contains("DescriptionLabel"), "TaskItemRow should expose task description in a reusable scene")
	assert_true(task_item_row_scene.contains("RewardLabel"), "TaskItemRow should expose rewards in a reusable scene")
	assert_true(task_item_row_scene.contains("ProgressBar"), "TaskItemRow should expose its scene-authored progress bar")
	assert_true(task_item_row_scene.contains("[node name=\"CompletedText\" type=\"Label\""), "TaskItemRow should keep completion copy as a scene label")
	assert_true(task_item_row_scene.contains("[node name=\"RewardTextTemplate\" type=\"Label\""), "TaskItemRow should keep reward templates as scene labels")
	assert_false(task_item_row_source.contains("@export"), "TaskItemRow should not require script exports for editor-authored text templates")
	assert_false(task_item_row_source.contains("%d/%d"), "TaskItemRow should not keep progress templates in script fallbacks")
	assert_false(task_item_row_source.contains("奖励："), "TaskItemRow should not keep reward copy in script fallbacks")
	assert_true(furniture_shop_item_row_scene.contains("[node name=\"Card\" type=\"VBoxContainer\""), "FurnitureShopItemRow should use a card layout for shop furniture")
	assert_true(furniture_shop_item_row_scene.contains("[node name=\"PreviewFrame\" type=\"PanelContainer\""), "FurnitureShopItemRow should show the furniture preview in a framed card area")
	assert_true(furniture_shop_item_row_scene.contains("PlaceButton"), "FurnitureShopItemRow should expose its place button in a reusable scene")
	assert_true(furniture_shop_item_row_scene.contains("[node name=\"PriceButtonTemplate\" type=\"Label\""), "FurnitureShopItemRow should keep price button templates as scene labels")
	assert_true(furniture_shop_item_row_scene.contains("text = \"%d\""), "FurnitureShopItemRow should preview price-only button copy")
	assert_true(furniture_shop_item_row_scene.contains("[node name=\"PlaceInsufficientText\" type=\"Label\""), "FurnitureShopItemRow should keep disabled button text as a scene label")
	assert_false(furniture_shop_item_row_source.contains("@export"), "FurnitureShopItemRow should not require script exports for editor-authored text templates")
	assert_false(furniture_shop_item_row_source.contains("%s %d"), "FurnitureShopItemRow should not keep item text templates in script fallbacks")
	assert_false(furniture_shop_item_row_source.contains("Not enough"), "FurnitureShopItemRow should not keep disabled button copy in script fallbacks")
	assert_true(room_furniture_item_row_scene.contains("MoveButton"), "RoomFurnitureItemRow should expose its move button in a reusable scene")
	assert_true(room_furniture_item_row_scene.contains("RecycleButton"), "RoomFurnitureItemRow should expose its recycle button in a reusable scene")
	assert_true(room_furniture_item_row_scene.contains("[node name=\"ItemTextTemplate\" type=\"Label\""), "RoomFurnitureItemRow should keep item text templates as scene labels")
	assert_true(room_furniture_item_row_scene.contains("[node name=\"FallbackFurnitureName\" type=\"Label\""), "RoomFurnitureItemRow should keep fallback furniture name in the scene")
	assert_false(room_furniture_item_row_source.contains("@export"), "RoomFurnitureItemRow should not require script exports for editor-authored text templates")
	assert_false(room_furniture_item_row_source.contains("位置"), "RoomFurnitureItemRow should not keep position copy in script fallbacks")
	assert_true(rent_room_row_scene.contains("TitleLabel"), "RentRoomRow should expose rent room title in a reusable scene")
	assert_true(rent_room_row_scene.contains("DetailLabel"), "RentRoomRow should expose rent room details in a reusable scene")
	assert_true(rent_room_row_scene.contains("[node name=\"EmptyTitleTemplate\" type=\"Label\""), "RentRoomRow should keep empty room title templates as scene labels")
	assert_true(rent_room_row_scene.contains("[node name=\"OccupiedTitleTemplate\" type=\"Label\""), "RentRoomRow should keep occupied room title templates as scene labels")
	assert_true(rent_room_row_scene.contains("[node name=\"DetailTemplate\" type=\"Label\""), "RentRoomRow should keep rent breakdown templates as scene labels")
	assert_false(rent_room_row_source.contains("@export"), "RentRoomRow should not require script exports for editor-authored text templates")
	assert_false(rent_room_row_source.contains("不产生租金"), "RentRoomRow should not keep empty detail copy in script fallbacks")
	assert_true(floor_overview_row_scene.contains("DetailLabel"), "FloorOverviewRow should expose floor details in a reusable scene")
	assert_true(floor_overview_row_scene.contains("[node name=\"DetailTemplate\" type=\"Label\""), "FloorOverviewRow should keep detail templates as scene labels")
	assert_true(floor_overview_row_scene.contains("[node name=\"BuiltStateText\" type=\"Label\""), "FloorOverviewRow should keep state labels in the scene")
	assert_false(floor_overview_row_source.contains("@export"), "FloorOverviewRow should not require script exports for editor-authored text templates")
	assert_false(floor_overview_row_source.contains("Lv.%d"), "FloorOverviewRow should not keep locked-state templates in script fallbacks")
	assert_true(tenant_overview_row_scene.contains("DetailLabel"), "TenantOverviewRow should expose tenant details in a reusable scene")
	assert_true(tenant_overview_row_scene.contains("[node name=\"TitleTemplate\" type=\"Label\""), "TenantOverviewRow should keep title templates as scene labels")
	assert_true(tenant_overview_row_scene.contains("[node name=\"DetailTemplate\" type=\"Label\""), "TenantOverviewRow should keep detail templates as scene labels")
	assert_false(tenant_overview_row_source.contains("@export"), "TenantOverviewRow should not require script exports for editor-authored text templates")
	assert_false(tenant_overview_row_source.contains("房间："), "TenantOverviewRow should not keep detail copy in script fallbacks")
	assert_true(tab_button_scene.contains("PanelTabButton"), "Panel tabs should be reusable button scenes")
	assert_false(tab_button_source.contains("@export"), "PanelTabButton should not require script exports for scene-authored tab ids")
	assert_true(action_button_scene.contains("PanelActionButton"), "Panel command buttons should be reusable scene nodes")
	assert_false(action_button_source.contains("custom_minimum_size ="), "PanelActionButton size should be authored per scene, not passed from parent scripts")
	assert_true(room_panel_scene.contains("TabRow"), "RoomPanel should expose its tab row in the scene")
	assert_true(room_panel_scene.contains("TabContent"), "RoomPanel should expose its tab content container")
	assert_true(room_panel_scene.contains("OverviewContent"), "RoomPanel should expose an editor-authored overview tab page")
	assert_true(room_panel_scene.contains("FurnitureContent"), "RoomPanel should expose an editor-authored furniture tab page")
	assert_true(room_panel_scene.contains("TenantContent"), "RoomPanel should expose an editor-authored tenant tab page")
	assert_true(room_panel_scene.contains("AddFurnitureButton"), "RoomPanel should expose its add-furniture button in the scene")
	assert_true(room_panel_scene.contains("RecruitTenantButton"), "RoomPanel should expose its recruit button in the scene")
	assert_true(room_panel_scene.contains("text = \"家具\""), "RoomPanel tabs should preview fixed labels in the scene")
	assert_true(room_panel_scene.contains("metadata/tab_id = \"furniture\""), "RoomPanel tab ids should be scene metadata")
	assert_true(room_panel_scene.contains("text = \"当前没有家具\""), "RoomPanel empty states should preview fixed copy in the scene")
	assert_true(room_panel_scene.contains("[node name=\"TemplateText\" type=\"Control\""), "RoomPanel should keep dynamic text templates as scene nodes")
	assert_true(room_panel_scene.contains("[node name=\"TitleTemplate\" type=\"Label\""), "RoomPanel should keep dynamic title templates as scene labels")
	assert_true(room_panel_scene.contains("[node name=\"BehaviorLabels\" type=\"Control\""), "RoomPanel should keep behavior display labels in the editable scene")
	assert_true(room_panel_scene.contains("metadata/behavior_key = \"wander\""), "RoomPanel behavior labels should be keyed through scene metadata")
	assert_true(room_panel_scene.contains("metadata/behavior_key = \"leaving\""), "RoomPanel should label tenant leaving state")
	assert_true(room_panel_scene.contains("metadata/behavior_key = \"away\""), "RoomPanel should label tenant away state")
	assert_true(room_panel_scene.contains("metadata/behavior_key = \"returning\""), "RoomPanel should label tenant returning state")
	assert_false(room_panel_source.contains("@export"), "RoomPanel should not require script exports for editor-authored text templates")
	assert_false(room_panel_source.contains("behavior_label_by_key = {"), "RoomPanel should not hide behavior display labels in script")
	assert_false(room_panel_source.contains("房间：%s"), "RoomPanel should not hard-code fixed title templates in script")
	assert_false(room_panel_source.contains("添加家具"), "RoomPanel should not hard-code fixed button copy in script")
	assert_true(shop_panel_scene.contains("ListRoot"), "FurnitureShopPanel should expose its list root")
	assert_true(shop_panel_scene.contains("[node name=\"ListRoot\" type=\"GridContainer\""), "FurnitureShopPanel should show shop items in a scene-authored two-column grid")
	assert_true(shop_panel_scene.contains("columns = 2"), "FurnitureShopPanel should preview two furniture cards per row")
	assert_true(shop_panel_scene.contains("[node name=\"TitleTemplate\" type=\"Label\""), "FurnitureShopPanel should keep title templates as scene labels")
	assert_true(shop_panel_scene.contains("[node name=\"FallbackRoomName\" type=\"Label\""), "FurnitureShopPanel should keep fallback room names as scene labels")
	assert_false(shop_panel_source.contains("@export"), "FurnitureShopPanel should not require script exports for editor-authored text templates")
	assert_false(shop_panel_source.contains("为 %s 添加家具"), "FurnitureShopPanel should not hide title templates in script")
	assert_true(tenant_panel_scene.contains("RegionContent"), "TenantPanel should expose its region selection content")
	assert_true(tenant_panel_scene.contains("CandidateContent"), "TenantPanel should expose its candidate content")
	assert_true(tenant_panel_scene.contains("TenantViewContent"), "TenantPanel should expose its tenant view content")
	assert_true(tenant_panel_scene.contains("BackToRegionsButton"), "TenantPanel should expose its back button in the scene")
	assert_true(tenant_panel_scene.contains("text = \"选择寻找租客的区域\""), "TenantPanel should preview region intro copy in the scene")
	assert_true(tenant_panel_scene.contains("[node name=\"TemplateText\" type=\"Control\""), "TenantPanel should keep dynamic text templates as scene nodes")
	assert_true(tenant_panel_scene.contains("[node name=\"CandidateDetailTemplate\" type=\"Label\""), "TenantPanel should keep candidate row templates as scene labels")
	assert_true(tenant_panel_scene.contains("text = \"倍率 %.2f"), "TenantPanel should preview candidate row templates in the scene")
	assert_true(tenant_panel_scene.contains("[node name=\"BehaviorLabels\" type=\"Control\""), "TenantPanel should keep behavior display labels in the editable scene")
	assert_true(tenant_panel_scene.contains("metadata/behavior_key = \"wander\""), "TenantPanel behavior labels should be keyed through scene metadata")
	assert_true(tenant_panel_scene.contains("metadata/behavior_key = \"leaving\""), "TenantPanel should label tenant leaving state")
	assert_true(tenant_panel_scene.contains("metadata/behavior_key = \"away\""), "TenantPanel should label tenant away state")
	assert_true(tenant_panel_scene.contains("metadata/behavior_key = \"returning\""), "TenantPanel should label tenant returning state")
	assert_false(tenant_panel_source.contains("@export"), "TenantPanel should not require script exports for editor-authored text templates")
	assert_true(tenant_panel_source.contains("func refresh()"), "TenantPanel should expose a refresh hook for live tenant state changes")
	assert_false(tenant_panel_source.contains("选择寻找租客的区域"), "TenantPanel should not hard-code region intro copy in script")
	assert_false(tenant_panel_source.contains("租金过高"), "TenantPanel should not hard-code candidate button copy in script")
	assert_false(tenant_panel_source.contains("behavior_label_by_key = {"), "TenantPanel should not hide behavior display labels in script")
	assert_true(overview_panel_scene.contains("SummaryGrid"), "ApartmentOverviewPanel should expose its summary grid")
	assert_true(overview_panel_scene.contains("ListRoot"), "ApartmentOverviewPanel should expose its list root")
	assert_true(overview_panel_scene.contains("EmptyTenantRow"), "ApartmentOverviewPanel should expose its empty tenant state")
	assert_true(overview_panel_scene.contains("text = \"公寓总览\""), "ApartmentOverviewPanel should preview its title in the scene")
	assert_true(overview_panel_scene.contains("text = \"楼层\""), "ApartmentOverviewPanel should preview tab labels in the scene")
	assert_true(overview_panel_scene.contains("[node name=\"TemplateText\" type=\"Control\""), "ApartmentOverviewPanel should keep dynamic text templates as scene nodes")
	assert_true(overview_panel_scene.contains("[node name=\"RentValueTemplate\" type=\"Label\""), "ApartmentOverviewPanel should expose rent value formatting as a scene label")
	assert_true(overview_panel_scene.contains("text = \"Lv.%d 还需 %d 经验\""), "ApartmentOverviewPanel should keep next-level templates in the scene")
	assert_false(overview_panel_source.contains("@export"), "ApartmentOverviewPanel should not require script exports for editor-authored text templates")
	assert_false(overview_panel_source.contains("Lv.%d 还需"), "ApartmentOverviewPanel should not hide next-level templates in script")
	assert_true(build_panel_scene.contains("StatsGrid"), "BuildConfirmPopup should expose its stat grid")
	assert_true(build_panel_scene.contains("CostCard"), "BuildConfirmPopup should expose cost card in the scene")
	assert_true(build_panel_scene.contains("StatusRow"), "BuildConfirmPopup should expose build status row in the scene")
	assert_true(build_panel_scene.contains("[node name=\"TitleTemplate\" type=\"Label\""), "BuildConfirmPopup should keep title templates as scene labels")
	assert_true(build_panel_scene.contains("text = \"需要金币\""), "BuildConfirmPopup should preview fixed card titles in the scene")
	assert_true(build_panel_scene.contains("[node name=\"CanBuildTitle\" type=\"Label\""), "BuildConfirmPopup should keep buildable-state copy as a scene label")
	assert_true(build_panel_scene.contains("[node name=\"InsufficientTitle\" type=\"Label\""), "BuildConfirmPopup should keep locked-state copy as a scene label")
	assert_true(build_panel_scene.contains("[node name=\"InsufficientDetailTemplate\" type=\"Label\""), "BuildConfirmPopup should keep locked-state detail templates as scene labels")
	assert_false(build_panel_source.contains("@export"), "BuildConfirmPopup should not require script exports for editor-authored text templates")
	assert_false(build_panel_source.contains("setup_panel(\"建造第"), "BuildConfirmPopup should not hide title templates in script")
	assert_false(build_panel_source.contains("cost_card.setup(\"需要金币\""), "BuildConfirmPopup should not hide fixed stat titles in script")
	assert_false(build_panel_source.contains("金币不足"), "BuildConfirmPopup should not hide locked-state copy in script")
	assert_false(build_panel_source.contains("可以建造"), "BuildConfirmPopup should not hide buildable-state copy in script")
	assert_true(income_panel_scene.contains("StatsGrid"), "IncomeDetailPanel should expose its stat grid")
	assert_true(income_panel_scene.contains("CoinCard"), "IncomeDetailPanel should expose its fixed coin card")
	assert_true(income_panel_scene.contains("NextIncomeRow"), "IncomeDetailPanel should expose its fixed next-income row")
	assert_true(income_panel_scene.contains("text = \"收益详情\""), "IncomeDetailPanel should preview its title in the scene")
	assert_true(income_panel_scene.contains("text = \"当前金币\""), "IncomeDetailPanel should preview fixed card titles in the scene")
	assert_true(income_panel_scene.contains("text = \"自动租金只按整数金币入账，小数会继续留在缓冲中。\""), "IncomeDetailPanel should preview fixed explanatory text in the scene")
	assert_true(income_panel_scene.contains("[node name=\"TemplateText\" type=\"Control\""), "IncomeDetailPanel should keep dynamic text templates as scene nodes")
	assert_true(income_panel_scene.contains("[node name=\"OfflineCapTitlePrefix\" type=\"Label\""), "IncomeDetailPanel should expose offline cap title prefix as a scene label")
	assert_true(income_panel_scene.contains("text = \"离线收益上限：\""), "IncomeDetailPanel should keep static title prefixes in the scene")
	assert_true(income_panel_scene.contains("[node name=\"NextIncomeTickTemplate\" type=\"Label\""), "IncomeDetailPanel should expose next-income template as a scene label")
	assert_true(income_panel_scene.contains("text = \"约 %.1f 秒后入账下 1 个整数金币\""), "IncomeDetailPanel should keep dynamic explanation templates in the scene")
	assert_false(income_panel_source.contains("setup_panel(\"收益详情\""), "IncomeDetailPanel should not overwrite the editor-authored panel title")
	assert_false(income_panel_source.contains("coin_card.setup(\"当前金币\""), "IncomeDetailPanel should not hide fixed stat titles in script")
	assert_false(income_panel_source.contains("自动租金只按整数金币入账"), "IncomeDetailPanel should not hide fixed explanatory text in script")
	assert_false(income_panel_source.contains("约 %.1f 秒后"), "IncomeDetailPanel should not hide dynamic explanation templates in script")
	assert_false(income_panel_source.contains("@export"), "IncomeDetailPanel should not require script exports for editor-authored text templates")
	assert_true(rent_panel_scene.contains("ListRoot"), "RentDetailPanel should expose its list root")
	assert_true(rent_panel_scene.contains("TotalRentCard"), "RentDetailPanel should expose the total rent card")
	assert_true(rent_panel_scene.contains("text = \"租金构成\""), "RentDetailPanel should preview its title in the scene")
	assert_true(rent_panel_scene.contains("[node name=\"RentValueTemplate\" type=\"Label\""), "RentDetailPanel should keep rent formatting as a scene label")
	assert_true(rent_panel_scene.contains("text = \"%.1f / 分钟\""), "RentDetailPanel should keep rent value templates in the scene")
	assert_false(rent_panel_source.contains("@export"), "RentDetailPanel should not require script exports for editor-authored text templates")
	assert_true(recycle_panel_scene.contains("MessageLabel"), "RecycleConfirmPopup should expose its message text")
	assert_true(recycle_panel_scene.contains("ConfirmButton"), "RecycleConfirmPopup should expose its confirm button")
	assert_true(recycle_panel_scene.contains("[node name=\"MessageTemplate\" type=\"Label\""), "RecycleConfirmPopup should keep message templates as scene labels")
	assert_true(recycle_panel_scene.contains("[node name=\"RefundTemplate\" type=\"Label\""), "RecycleConfirmPopup should keep refund templates as scene labels")
	assert_false(recycle_panel_source.contains("@export"), "RecycleConfirmPopup should not require script exports for editor-authored text templates")
	assert_false(recycle_panel_source.contains("确认回收 %s"), "RecycleConfirmPopup should not hide message templates in script")
	assert_false(recycle_panel_source.contains("将返还 %d"), "RecycleConfirmPopup should not hide refund templates in script")
	assert_true(task_panel_scene.contains("TaskListRoot"), "TaskPanel should expose its task list root")
	assert_true(task_panel_scene.contains("EmptyTaskRow"), "TaskPanel should expose its empty task state")
	assert_true(task_panel_scene.contains("text = \"当前没有进行中的任务\""), "TaskPanel should preview empty-state copy in the scene")
	assert_true(reward_panel_scene.contains("ListRoot"), "RewardPanel should expose its list root")
	assert_true(reward_panel_scene.contains("OfflineIncomeCard"), "RewardPanel should expose its offline income card")
	assert_true(reward_panel_scene.contains("TenantRefreshRow"), "RewardPanel should expose its tenant refresh description row")
	assert_true(reward_panel_scene.contains("OfflineClaimButton"), "RewardPanel should expose its claim button")
	assert_true(reward_panel_scene.contains("text = \"福利\""), "RewardPanel should preview its title in the scene")
	assert_true(reward_panel_scene.contains("text = \"领取离线收益\""), "RewardPanel should preview fixed button copy in the scene")
	assert_true(reward_panel_scene.contains("[node name=\"OfflineIncomeValueTemplate\" type=\"Label\""), "RewardPanel should keep offline income value templates as scene labels")
	assert_false(reward_panel_source.contains("@export"), "RewardPanel should not require script exports for editor-authored text templates")
	assert_false(reward_panel_source.contains("领取离线收益"), "RewardPanel should not hard-code fixed button copy in script")
	assert_true(settings_panel_scene.contains("SfxRow"), "SettingsPanel should expose its sound row")
	assert_true(settings_panel_scene.contains("PrivacyRow"), "SettingsPanel should expose its policy row")
	assert_true(settings_panel_scene.contains("SaveButton"), "SettingsPanel should expose its save button")
	assert_true(settings_panel_scene.contains("ResetButton"), "SettingsPanel should expose its reset button")
	assert_true(settings_panel_scene.contains("text = \"设置\""), "SettingsPanel should preview its title in the scene")
	assert_true(settings_panel_scene.contains("text = \"音效\""), "SettingsPanel should preview fixed row copy in the scene")
	assert_false(settings_panel_source.contains("音效"), "SettingsPanel should not hard-code fixed row copy in script")
	assert_true(offline_panel_scene.contains("OfflineInfoRow"), "OfflineRewardPopup should expose its offline info row")
	assert_true(offline_panel_scene.contains("AmountCard"), "OfflineRewardPopup should expose its amount card")
	assert_true(offline_panel_scene.contains("ClaimButton"), "OfflineRewardPopup should expose its claim button")
	assert_true(offline_panel_scene.contains("DoubleClaimButton"), "OfflineRewardPopup should expose its double-claim button")
	assert_true(offline_panel_scene.contains("[node name=\"ButtonRow\" type=\"HBoxContainer\""), "OfflineRewardPopup should keep claim buttons side by side")
	assert_true(offline_panel_scene.contains("[node name=\"ButtonRow\" type=\"HBoxContainer\" parent=\"PanelBox\""), "OfflineRewardPopup action buttons should stay fixed outside the scroll container")
	assert_true(offline_panel_source.contains("get_node_or_null(\"PanelBox/ButtonRow\")"), "OfflineRewardPopup should bind fixed action buttons from PanelBox/ButtonRow")
	assert_true(offline_panel_source.contains("button_row.get_node_or_null(\"ClaimButton\")"), "OfflineRewardPopup should resolve claim buttons from the fixed action row")
	assert_false(offline_panel_source.contains("ButtonRow/ClaimButton"), "OfflineRewardPopup should not look for action buttons inside scrolled content")
	assert_true(offline_panel_scene.contains("[node name=\"OfflineDurationTitleTemplate\" type=\"Label\""), "OfflineRewardPopup should keep dynamic duration templates as scene labels")
	assert_false(offline_panel_source.contains("@export"), "OfflineRewardPopup should not require script exports for editor-authored text templates")
	assert_true(offline_panel_scene.contains("Boost_off.png"), "OfflineRewardPopup should preview the offline-duration icon")
	assert_true(offline_panel_scene.contains("text = \"你离线了 0 分钟\""), "OfflineRewardPopup should preview the offline duration title")
	assert_true(offline_panel_scene.contains("text = \"离线收益按当前总租金折算，并受离线时长上限限制。\""), "OfflineRewardPopup should preview the offline reward explanation")
	assert_true(offline_panel_scene.contains("text = \"获得金币\""), "OfflineRewardPopup should preview the coin amount title")
	assert_true(offline_panel_scene.contains("text = \"双倍领取\""), "OfflineRewardPopup should preview compact double-claim button copy in the scene")
	assert_false(offline_panel_source.contains("你离线了"), "OfflineRewardPopup should not hard-code duration templates in script")
	assert_false(offline_panel_source.contains("看广告双倍领取"), "OfflineRewardPopup should not hard-code button copy in script")
	assert_false(factory_source.contains(".instantiate()"), "UIPanelFactory should not instantiate UI structure")
	assert_false(factory_source.contains("preload(\"res://scenes/ui/"), "UIPanelFactory should not hide reusable UI scenes behind generic add helpers")
	assert_false(factory_source.contains("func make_panel"), "UIPanelFactory should not build panel skeletons in code")
	assert_false(factory_source.contains("func add_button"), "UIPanelFactory should not create command buttons in code")
	assert_false(factory_source.contains("func add_stat_card"), "UIPanelFactory should not create stat cards in code")
	assert_false(factory_source.contains("func add_icon_row"), "UIPanelFactory should not create info rows in code")
	assert_false(factory_source.contains("func add_progress_card"), "UIPanelFactory should not create progress cards in code")


func test_ui_scripts_do_not_build_control_skeletons() -> void:
	var forbidden_tokens := [
		"Button.new(",
		"Label.new(",
		"PanelContainer.new(",
		"HBoxContainer.new(",
		"VBoxContainer.new(",
		"GridContainer.new(",
		"TextureRect.new(",
		"ScrollContainer.new(",
		"ColorRect.new("
	]
	for path in _presentation_script_paths():
		var source := FileAccess.get_file_as_string(path)
		for token in forbidden_tokens:
			assert_false(source.contains(token), "%s should not build UI skeletons with %s" % [path, token])


func test_ui_scripts_do_not_hide_fixed_layout_or_style() -> void:
	var forbidden_tokens := [
		"StyleBox",
		"add_theme_",
		"theme_override",
		"set_anchors",
		"anchor_left",
		"anchor_top",
		"anchor_right",
		"anchor_bottom",
		"offset_left",
		"offset_top",
		"offset_right",
		"offset_bottom",
		"custom_minimum_size",
		".position =",
		".size =",
		"stretch_mode",
		"mouse_filter",
		"focus_mode",
		"pivot_offset"
	]
	var allowed_tokens_by_path := {
		"res://scripts/ui/PlacementOverlay.gd": [
			"custom_minimum_size",
			".position =",
			".size ="
		]
	}
	for path in _presentation_script_paths():
		var source := FileAccess.get_file_as_string(path)
		var allowed_tokens: Array = allowed_tokens_by_path.get(path, [])
		for token in forbidden_tokens:
			if allowed_tokens.has(token):
				continue
			assert_false(source.contains(token), "%s should keep fixed UI layout/style in .tscn, not script token %s" % [path, token])


func test_project_rules_require_editor_authored_ui() -> void:
	var agents := FileAccess.get_file_as_string("res://AGENTS.md")
	var technical_rules := FileAccess.get_file_as_string("res://.agents/rules/technical.md")
	var trd := FileAccess.get_file_as_string("res://docs/TRD.md")
	var data_rules := FileAccess.get_file_as_string("res://.agents/rules/data-config.md")
	var tilemap_plan := FileAccess.get_file_as_string("res://docs/APARTMENT_TILEMAP_MIGRATION.md")
	assert_true(agents.contains("项目当前处于开发阶段"), "AGENTS should mark this project as development-stage")
	assert_true(agents.contains("不需要兼容旧配置或旧存档"), "AGENTS should direct agents not to preserve old config/save compatibility by default")
	assert_true(technical_rules.contains("UI 层必须在 `.tscn` 中搭建"), "technical rules should require editor-authored UI")
	assert_true(technical_rules.contains("禁止在 UI 脚本中用 `Button.new()`"), "technical rules should forbid scripted UI skeletons")
	assert_true(technical_rules.contains("固定 `StyleBox`"), "technical rules should forbid fixed UI skins in scripts")
	assert_true(trd.contains("UI 层以编辑器所见即所得为准"), "TRD should document WYSIWYG UI workflow")
	assert_true(data_rules.contains("固定 UI 结构、默认按钮文案、面板标题"), "data-config rules should allow fixed preview copy in .tscn")
	assert_true(data_rules.contains("GDScript 不应硬编码固定中文 UI 文案"), "data-config rules should keep fixed copy out of scripts")
	assert_true(data_rules.contains("data/behavior_aliases.json"), "data rules should include behavior alias compatibility config")
	assert_true(trd.contains("公寓主体应改为 TileMap / TileMapLayer 优先"), "TRD should track the apartment TileMap migration")
	assert_true(trd.contains("docs/APARTMENT_TILEMAP_MIGRATION.md"), "TRD should link the apartment TileMap migration plan")
	assert_true(trd.contains("behavior_aliases.json"), "TRD should list the behavior alias config file")
	assert_true(tilemap_plan.contains("目标状态"), "Apartment TileMap migration plan should define the target state")
	assert_true(tilemap_plan.contains("验收标准"), "Apartment TileMap migration plan should define acceptance criteria")


func test_placement_overlay_is_scene_based_not_grid_panel() -> void:
	var overlay_source := FileAccess.get_file_as_string("res://scripts/ui/PlacementOverlay.gd")
	var overlay_scene := FileAccess.get_file_as_string("res://scenes/ui/PlacementOverlay.tscn")
	var room_source := FileAccess.get_file_as_string("res://scripts/building/Room.gd")
	var popup_source := FileAccess.get_file_as_string("res://scripts/ui/PopupLayer.gd")
	var main_source := FileAccess.get_file_as_string("res://scenes/main/Main.gd")
	assert_true(overlay_scene.contains("[node name=\"PlacementOverlay\" type=\"Control\"]"), "placement overlay should be a scene-authored Control, not a full AppPanel")
	assert_true(overlay_scene.contains("[node name=\"PlaceTitlePrefix\" type=\"Label\""), "placement overlay state text should be authored in the scene")
	assert_true(overlay_scene.contains("[node name=\"MoveConfirmText\" type=\"Label\""), "placement move confirm text should be authored in the scene")
	assert_true(overlay_scene.contains("拖动 %s 到合适位置"), "placement hint copy should be previewable in the scene")
	assert_true(overlay_scene.contains("mouse_filter = 0"), "placement overlay should capture direct drag input over room buttons")
	assert_false(overlay_source.contains("extends \"res://scripts/ui/AppPanel.gd\""), "placement should not open as a full blocking AppPanel")
	assert_false(overlay_source.contains("GridContainer.new()"), "placement should not use a separate grid-selection panel")
	assert_false(overlay_source.contains("set_anchors_preset"), "placement overlay should keep its full-rect layout in the scene")
	assert_false(overlay_source.contains("_fill_parent"), "placement overlay should not repair fixed layout at runtime")
	assert_false(overlay_source.contains("拖动 %s 到合适位置"), "placement hint copy should not be hidden in script")
	assert_true(overlay_source.contains("func _gui_input"), "placement should handle drag input before room buttons consume it")
	assert_true(overlay_source.contains("_position_preview_under_pointer"), "placement preview should follow the active pointer during drag")
	assert_true(overlay_source.contains("floating_controls.visible = false"), "placement should hide floating controls while dragging")
	assert_true(overlay_source.contains("floating_controls.visible = true"), "placement should restore floating controls after drag release")
	assert_true(overlay_source.contains("show_placement_grid"), "placement should still update hidden target-room placement state")
	assert_true(room_source.contains("placement_grid_layer.visible = false"), "Room should keep the placement grid hidden")
	assert_false(room_source.contains("draw_rect(cell_rect"), "Room should not draw every placement grid cell")
	assert_true(room_source.contains("world_position_to_placement_grid"), "Room should translate scene taps into furniture-aware placement grid cells")
	assert_true(room_source.contains("get_preview_position"), "Room should provide scene preview positions")
	assert_true(room_source.contains("UIManager.current_state != UIManager.UIState.NORMAL"), "Room clicks should not steal placement-state input")
	assert_true(popup_source.contains("open_overlay"), "PopupLayer should support transparent placement overlays")
	assert_true(main_source.contains("popup_layer.open_overlay(PLACEMENT_OVERLAY_SCENE)"), "Main should open placement through the scene overlay path")
	assert_true(main_source.contains("building_view.focus_room(room_id)"), "Main should focus the target room before scene placement")
	assert_true(main_source.contains("building_view.clear_focus()"), "Main should restore building focus after placement")


func test_room_flow_panels_are_bottom_sheets() -> void:
	var app_panel_source := FileAccess.get_file_as_string("res://scripts/ui/AppPanel.gd")
	assert_false(app_panel_source.contains("func use_bottom_sheet"), "AppPanel should not position flow panels at runtime")
	for path in [
		"res://scenes/ui/RoomPanel.tscn",
		"res://scenes/ui/TenantPanel.tscn",
		"res://scenes/ui/BuildConfirmPopup.tscn"
	]:
		var scene_source := FileAccess.get_file_as_string(path)
		assert_true(scene_source.contains("anchors_preset = 12"), "%s should keep the apartment visible as an editor-authored bottom sheet" % path)
		assert_true(scene_source.contains("anchor_top = 1.0"), "%s should anchor to the bottom edge in the scene" % path)
		assert_true(scene_source.contains("offset_bottom = -10.0"), "%s should keep its bottom margin in the scene" % path)
	for path in [
		"res://scenes/ui/FurnitureShopPanel.tscn",
		"res://scenes/ui/OfflineRewardPopup.tscn",
		"res://scenes/ui/RecycleConfirmPopup.tscn"
	]:
		var scene_source := FileAccess.get_file_as_string(path)
		assert_true(scene_source.contains("anchors_preset = 8"), "%s should keep centered popup layout in the scene" % path)


func test_furniture_in_room_supports_scene_long_press_move() -> void:
	var furniture_scene := FileAccess.get_file_as_string("res://scenes/furniture/Furniture.tscn")
	var preview_scene := FileAccess.get_file_as_string("res://scenes/furniture/FurniturePreview.tscn")
	var furniture_source := FileAccess.get_file_as_string("res://scripts/furniture/Furniture.gd")
	var preview_source := FileAccess.get_file_as_string("res://scripts/furniture/FurniturePreview.gd")
	var room_source := FileAccess.get_file_as_string("res://scripts/building/Room.gd")
	assert_true(furniture_source.contains("LONG_PRESS_SECONDS"), "Furniture should expose a long-press operation affordance")
	assert_true(furniture_source.contains("UIManager.start_move_existing"), "Long-pressing furniture in the room should enter move mode")
	assert_true(furniture_scene.contains("mouse_filter = 0"), "Furniture input priority should be authored in Furniture.tscn")
	assert_true(furniture_scene.contains("stretch_mode = 5"), "Furniture texture stretch should be authored in Furniture.tscn")
	assert_true(furniture_scene.contains("pivot_offset = Vector2(13, 13)"), "Furniture pivot should be authored in Furniture.tscn")
	assert_true(furniture_scene.contains("[node name=\"TemplateText\" type=\"Control\""), "Furniture fallback tooltip copy should be authored as scene text")
	assert_true(furniture_scene.contains("[node name=\"FallbackFurnitureName\" type=\"Label\""), "Furniture should expose fallback tooltip text in Furniture.tscn")
	assert_true(preview_scene.contains("pivot_offset = Vector2(28, 28)"), "FurniturePreview pivot should be authored in FurniturePreview.tscn")
	assert_false(furniture_source.contains("@export"), "Furniture should not require script exports for scene-authored presentation")
	assert_false(preview_source.contains("@export"), "FurniturePreview should not require script exports for scene-authored presentation")
	assert_false(furniture_source.contains("override_configured_asset"), "Furniture should use configured asset data instead of script-level visual overrides")
	assert_false(preview_source.contains("override_configured_asset"), "FurniturePreview should use configured asset data instead of script-level visual overrides")
	assert_false(furniture_source.contains("custom_minimum_size ="), "Furniture fixed size should stay in Furniture.tscn")
	assert_false(furniture_source.contains("stretch_mode ="), "Furniture stretch mode should stay in Furniture.tscn")
	assert_false(furniture_source.contains("pivot_offset ="), "Furniture pivot should stay in Furniture.tscn")
	assert_false(furniture_source.contains("\"家具\""), "Furniture fallback tooltip copy should not be hard-coded in script")
	assert_true(preview_source.contains("VALID_OUTLINE_COLOR"), "FurniturePreview should expose valid placement with its own outline")
	assert_true(preview_source.contains("INVALID_OUTLINE_COLOR"), "FurniturePreview should expose invalid placement with its own outline")
	assert_true(preview_source.contains("draw_rect"), "FurniturePreview should draw placement validity feedback on the preview itself")
	assert_true(room_source.contains("view_data[\"room_id\"] = room_id"), "Room should bind furniture visuals back to their room")
	assert_true(room_source.contains("_asset_region_size"), "Furniture visuals should preserve atlas-region proportions")
