@tool
extends "res://tests/support/TestSuiteBase.gd"

func suite_name() -> String:
	return "tenant_ai"

func test_tenant_uses_character_body_click_area_and_strict_animations() -> void:
	var tenant_scene := FileAccess.get_file_as_string("res://scenes/tenant/Tenant.tscn")
	var tenant_source := FileAccess.get_file_as_string("res://scripts/tenant/Tenant.gd")
	var room_source := FileAccess.get_file_as_string("res://scripts/building/Room.gd")
	var building_view_source := FileAccess.get_file_as_string("res://scripts/building/BuildingView.gd")
	var main_source := FileAccess.get_file_as_string("res://scenes/main/Main.gd")
	var locator_source := FileAccess.get_file_as_string("res://scripts/tenant/TenantRoomLocator.gd")
	var ai_source := FileAccess.get_file_as_string("res://scripts/tenant/TenantAI.gd")
	var need_bubble_scene := FileAccess.get_file_as_string("res://scenes/tenant/NeedBubble.tscn")
	var need_bubble_source := FileAccess.get_file_as_string("res://scripts/tenant/NeedBubble.gd")
	var emote_scene := FileAccess.get_file_as_string("res://scenes/tenant/TenantEmote.tscn")
	var emote_source := FileAccess.get_file_as_string("res://scripts/tenant/TenantEmote.gd")
	assert_true(tenant_scene.contains("[node name=\"Tenant\" type=\"CharacterBody2D\""), "Tenant should be a map CharacterBody2D scene")
	assert_true(tenant_scene.contains("AnimatedSprite2D"), "Tenant should reserve AnimatedSprite2D for future spritesheets")
	assert_true(tenant_scene.contains("NeedBubble.tscn"), "Tenant should instance the reusable NeedBubble scene")
	assert_true(tenant_scene.contains("TenantAI.gd"), "Tenant should own a per-instance AI state machine")
	assert_true(tenant_scene.contains("[node name=\"TenantAI\" type=\"Node\""), "TenantAI should be a scene child, not a global Main loop")
	assert_true(tenant_scene.contains("[node name=\"ClickArea\" type=\"Area2D\""), "Tenant clicks should be routed through a scene-authored ClickArea")
	assert_true(tenant_scene.contains("[node name=\"ClickShape\" type=\"CollisionShape2D\""), "Tenant ClickArea should expose its hit shape in the scene")
	assert_true(tenant_scene.contains("position = Vector2(28, 56)"), "Tenant standalone preview should place the character inside the viewport")
	assert_true(tenant_scene.contains("position = Vector2(0, -9)"), "Tenant avatar should compensate for transparent padding in the unscaled 32x42 NPC frame")
	assert_true(tenant_scene.contains("region = Rect2(0, 32, 32, 32)"), "Tenant atlas frames should match the configured 32x42 Pixel Spaces NPC grid")
	assert_false(tenant_scene.contains("region = Rect2(0, 32, 16, 32)"), "Tenant atlas frames should not override the configured 32x42 NPC grid")
	assert_false(tenant_scene.contains("scale = Vector2(1.5, 1.5)"), "Tenant should render the configured 32x42 NPC frames at scene scale")
	assert_true(tenant_scene.contains("sprite_frames = SubResource"), "Tenant avatar frames should be prebuilt on AvatarSprite in Tenant.tscn")
	assert_true(tenant_scene.contains("\"name\": &\"walk\""), "Tenant.tscn should prebuild a walk animation on AvatarSprite")
	assert_true(tenant_scene.contains("BehaviorAnimationMap"), "Tenant behavior-to-animation bindings should be authored in Tenant.tscn")
	assert_true(tenant_scene.contains("metadata/default_avatar_animation = \"idle\""), "Tenant default avatar animation should be scene metadata")
	assert_true(tenant_scene.contains("metadata/avatar_animation = \"walk\""), "Tenant walk animation binding should be scene metadata")
	assert_false(tenant_scene.contains("metadata/moves = true"), "Tenant movement should live in TenantAI, not animation metadata")
	assert_false(tenant_scene.contains("metadata/behavior_keys = \"wander,recruited,entertainment,eat,clean,study,relax\""), "Only common visible actions should bind to avatar animations")
	assert_true(need_bubble_scene.contains("[node name=\"NeedBubble\" type=\"Control\""), "NeedBubble should be a previewable Control scene")
	assert_true(need_bubble_scene.contains("BubbleAnimation\" type=\"AnimatedSprite2D\""), "NeedBubble should reserve an AnimatedSprite2D bubble node")
	assert_true(need_bubble_scene.contains("IconRoot"), "NeedBubble should expose an icon root in the scene")
	assert_true(need_bubble_scene.contains("SleepIcon"), "NeedBubble should expose behavior icon nodes in the scene")
	assert_true(need_bubble_scene.contains("metadata/behavior_key = \"sleep\""), "NeedBubble behavior icons should be bound through scene metadata")
	assert_true(need_bubble_scene.contains("metadata/behavior_keys = \"relax,happy\""), "NeedBubble shared icons should be bound through scene metadata")
	assert_true(need_bubble_scene.contains("\"loop\": false"), "NeedBubble animation should be non-looping so icons can appear after it finishes")
	assert_true(emote_scene.contains("[node name=\"TenantEmote\" type=\"Control\"]"), "TenantEmote should be a previewable Control scene")
	assert_true(emote_scene.contains("EmoteAnimation\" type=\"AnimatedSprite2D\""), "TenantEmote should reserve an AnimatedSprite2D emote node")
	assert_true(emote_scene.contains("IconRoot"), "TenantEmote should expose an icon root in the scene")
	assert_true(emote_scene.contains("HappyIcon"), "TenantEmote should expose emote icon nodes in the scene")
	assert_true(emote_scene.contains("metadata/emote_key = \"happy\""), "TenantEmote icons should be bound through scene metadata")
	assert_true(emote_scene.contains("\"loop\": false"), "TenantEmote animation should be non-looping so icons can appear after it finishes")
	assert_true(tenant_source.contains("need_bubble.show_behavior"), "Tenant behavior bubble should be delegated to NeedBubble")
	assert_true(tenant_source.contains("UIManager.open_tenant_panel"), "Clicking an in-room tenant should open tenant context")
	assert_true(tenant_source.contains("_play_avatar_animation"), "Tenant should actively play the behavior animation")
	assert_true(tenant_source.contains("GameEvents.tenant_behavior_changed.connect"), "Tenant animation should refresh on ordinary AI behavior changes")
	assert_true(tenant_source.contains("TenantAI"), "Tenant should bind its scene-authored AI node")
	assert_true(tenant_source.contains("ClickArea"), "Tenant should bind the scene-authored click area")
	assert_true(tenant_source.contains("func _apply_avatar_asset"), "Tenant should apply configured avatar assets at runtime")
	assert_true(tenant_source.contains("func _apply_avatar_offset"), "Tenant should centralize avatar offset application for config-driven tuning")
	assert_true(tenant_source.contains("body_shape.position = offset"), "Tenant avatar offset should keep the body collision aligned with the visual")
	assert_true(tenant_source.contains("click_shape.position = offset"), "Tenant avatar offset should keep the click shape aligned with the visual")
	assert_true(tenant_source.contains("ConfigManager.get_tenant_data(tenant_id)"), "Tenant should source avatar config from tenants.json")
	assert_true(tenant_source.contains("AssetResolver.apply_asset_to_animated_sprite"), "Tenant should rebuild AvatarSprite frames through AssetResolver")
	assert_true(tenant_source.contains("push_error(\"Tenant AvatarSprite is missing animation"), "Missing tenant animations should be explicit errors")
	assert_true(ai_source.contains("enum AIState"), "TenantAI should use an explicit state machine")
	assert_true(ai_source.contains("AIState.IDLE"), "TenantAI should support idle")
	assert_true(ai_source.contains("AIState.WALK"), "TenantAI should support walking")
	assert_true(ai_source.contains("AIState.JUMP"), "TenantAI should support jumping")
	assert_true(ai_source.contains("AIState.BUBBLE_ACTION"), "TenantAI should support bubble-only actions")
	assert_false(ai_source.contains("AIState.ENTERING"), "TenantAI should not force home tenants through startup offscreen entry routes")
	assert_true(ai_source.contains("AIState.LEAVING"), "TenantAI should support leaving routes")
	assert_true(ai_source.contains("AIState.AWAY"), "TenantAI should support hidden away state")
	assert_true(ai_source.contains("AIState.RETURNING"), "TenantAI should support returning routes")
	assert_true(ai_source.contains("_sync_from_current_behavior"), "TenantAI setup should restore current state without overwriting observed behavior")
	assert_false(ai_source.contains("startup_entry_tenant_ids"), "TenantAI should not track startup offscreen entry sessions")
	assert_false(ai_source.contains("startup_entry_active_tenant_ids"), "TenantAI should not hide in-room tenants behind startup entry state")
	assert_false(ai_source.contains("startup_entry_refresh_active"), "TenantAI should not have a loaded-state offscreen entry window")
	assert_false(ai_source.contains("static func reset_startup_entry_session"), "TenantAI should not need startup entry reset hooks")
	assert_false(ai_source.contains("static func begin_startup_entry_refresh"), "TenantAI should not expose startup entry refresh hooks")
	assert_false(ai_source.contains("static func end_startup_entry_refresh"), "TenantAI should not expose startup entry refresh hooks")
	assert_false(ai_source.contains("static func is_startup_entry_active"), "TenantAI should not make room rendering depend on startup route state")
	assert_false(ai_source.contains("_mark_startup_entry_finished"), "TenantAI should not clean up removed startup entry flags")
	assert_false(ai_source.contains("_run_startup_entry_route"), "TenantAI should not own a startup route from offscreen")
	assert_true(ai_source.contains("_run_leaving_route"), "TenantAI should own the deterministic leaving route")
	assert_true(ai_source.contains("_run_returning_route"), "TenantAI should own the deterministic returning route")
	assert_true(ai_source.contains("not tenant.ai_position_initialized"), "Home tenants should only initialize position once")
	assert_true(ai_source.contains("TenantRoomLocator.spawn_position(_room(), tenant_id)"), "Home tenants should initialize at stable in-room floor-line coordinates")
	assert_true(ai_source.contains("func _visible_return_start_position"), "Returning tenants should choose a visible route start instead of offscreen")
	assert_true(ai_source.contains("tenant.position = _visible_return_start_position"), "Hidden returning tenants should resume from a visible route anchor")
	assert_false(ai_source.contains("_run_entry_route(false, true)"), "Startup entry should not reuse returning routes from offscreen")
	assert_false(ai_source.contains("get_offscreen_left_world_position(exit_position.y)"), "Returning tenants should not be reset to offscreen just because they are hidden")
	assert_true(ai_source.contains("func _leave_through_exit_door"), "TenantAI should make exit-door leaving a reusable route step")
	assert_true(ai_source.contains("func _enter_through_exit_door"), "TenantAI should make exit-door entering a reusable route step")
	assert_true(ai_source.contains("func _enter_elevator_at_floor"), "TenantAI should make source elevator entry a reusable route step")
	assert_true(ai_source.contains("func _exit_elevator_at_floor"), "TenantAI should make target elevator exit a reusable route step")
	assert_true(ai_source.contains("func _play_route_door_open"), "TenantAI should make ordinary room and exit doors idle only while opening")
	assert_true(ai_source.contains("_play_route_idle()\n\tawait _play_traffic_door(door, true, duration)"), "TenantAI should switch to idle before ordinary doors open")
	assert_false(ai_source.contains("_play_route_idle()\n\tawait _play_traffic_door(door, false"), "TenantAI should not play idle while ordinary doors close")
	assert_true(ai_source.contains("var hide_progress := _elevator_close_hide_progress()"), "TenantAI should hide tenants near the end of source elevator close")
	assert_true(ai_source.contains("var show_progress := _elevator_open_show_progress()"), "TenantAI should show tenants near the end of target elevator open")
	assert_true(ai_source.contains("tenant.visible = false"), "TenantAI should hide tenants during source elevator close")
	assert_true(ai_source.contains("tenant.visible = true"), "TenantAI should show tenants during target elevator open")
	assert_false(ai_source.contains("_ai_paused"), "TenantAI should not pause all movement during furniture placement")
	assert_false(ai_source.contains("tenant.position == Vector2.ZERO"), "TenantAI should not use origin as an uninitialized-position sentinel")
	assert_true(ai_source.contains("GameState.set_tenant_presence"), "TenantAI routes should sync persisted presence state")
	assert_true(ai_source.contains("get_tenant_world_layer"), "TenantAI should promote route movement to the building tenant layer")
	assert_true(ai_source.contains("get_offscreen_left_world_position"), "TenantAI should finish leaving routes at the shared offscreen mark")
	assert_true(ai_source.contains("TenantRoomLocator.spawn_position"), "TenantAI should spawn from the room floor line")
	assert_false(room_source.contains("TenantAI.is_startup_entry_active"), "Room should not gate HOME tenant rendering on startup route state")
	assert_true(tenant_source.contains("TENANT_VIEW_GROUP"), "Tenant views should be discoverable for scene-wide deduplication")
	assert_true(tenant_source.contains("set_meta(META_TENANT_ID"), "Tenant views should expose tenant_id metadata for ownership checks")
	assert_true(room_source.contains("func ensure_home_tenant_view"), "Room should expose a targeted HOME tenant view hook")
	assert_false(room_source.contains("for tenant_id in GameState.tenants.keys()"), "Room should not auto-create every tenant while binding visual layers")
	assert_true(building_view_source.contains("func _ensure_tenant_views"), "BuildingView should own tenant visual synchronization")
	assert_true(building_view_source.contains("func _tenant_views_by_id"), "BuildingView should group tenant view instances by tenant_id")
	assert_true(building_view_source.contains("_queue_free_other_tenant_views"), "BuildingView should remove duplicate tenant views after choosing the owner instance")
	assert_true(building_view_source.contains("ensure_home_tenant_view"), "BuildingView should place HOME tenants back into the room visual layer")
	assert_false(building_view_source.contains("func _ensure_world_tenants"), "BuildingView should not keep the old route-only tenant spawner")
	assert_true(room_source.contains("tenant_view.visible = false"), "Room should hide tenant instances before adding them to the scene so preview coordinates never flash")
	assert_true(room_source.contains("visual_layer.add_child(tenant_view)\n\ttenant_view.setup(tenant_id, room_id)"), "Room should add tenant views before setup so TenantAI can resolve the room and place them safely")
	assert_true(ai_source.contains("TenantRoomLocator.wander_target_position"), "TenantAI should wander along the room floor line")
	assert_true(ai_source.contains("TenantRoomLocator.furniture_use_position"), "TenantAI should derive furniture use positions from the continuous floor line")
	assert_true(locator_source.contains("class_name TenantRoomLocator"), "Tenant room positions should live in a dedicated floor-line locator")
	assert_true(locator_source.contains("room.get(\"door_side\""), "Tenant door route points should follow the configured room door side")
	assert_false(locator_source.contains("door_cells_for_layer(room"), "Tenant floor-line positions should not avoid old door cells after doors became outward-opening")
	assert_true(need_bubble_source.contains("await bubble_animation.animation_finished"), "NeedBubble should reveal icons only after the bubble animation finishes")
	assert_true(emote_source.contains("await emote_animation.animation_finished"), "TenantEmote should reveal icons only after the emote animation finishes")
	assert_false(tenant_scene.contains("behavior_animation_map = {"), "Tenant.tscn should not keep script-exported behavior animation config")
	assert_false(tenant_scene.contains("ColorFallback"), "Tenant should not keep a color fallback visual")
	assert_false(tenant_source.contains("BEHAVIOR_ANIMATION"), "Tenant behavior animation bindings should stay in Tenant.tscn metadata")
	assert_false(tenant_source.contains("@export"), "Tenant should not expose avatar frame or animation config in script")
	assert_false(tenant_source.contains("_avatar_asset_from_config"), "Tenant should use the shared AssetResolver path instead of local frame builders")
	assert_false(tenant_source.contains("_frame_entries"), "Tenant should not generate animation frame entries in script")
	assert_false(tenant_source.contains("@export var avatar_scale"), "Tenant fixed avatar scale should stay in Tenant.tscn")
	assert_false(tenant_source.contains("set_avatar_scale"), "Rooms should not tune tenant visual layout at runtime")
	assert_false(tenant_source.contains("custom_minimum_size ="), "Tenant fixed size should stay in Tenant.tscn")
	assert_false(tenant_source.contains("mouse_filter ="), "Tenant mouse filtering should stay in Tenant.tscn")
	assert_false(tenant_source.contains("focus_mode ="), "Tenant focus mode should stay in Tenant.tscn")
	assert_false(tenant_source.contains("need_bubble.position"), "NeedBubble placement should stay in NeedBubble.tscn")
	assert_false(tenant_source.contains("fallback_animation"), "Tenant should not fall back to another avatar animation")
	assert_false(tenant_source.contains("color_fallback"), "Tenant should not toggle fallback visuals")
	assert_false(tenant_source.contains("accept_event()"), "Tenant should not use Control GUI event handling")
	assert_false(tenant_source.contains("Rect2(Vector2.ZERO, size)"), "Tenant click checks should not depend on Control size")
	assert_false(tenant_source.contains("func _gui_input"), "Tenant root should not use Control _gui_input")
	assert_false(tenant_source.contains("position = base_position"), "Tenant should not snap back to its spawn point every frame")
	assert_false(tenant_source.contains("current_behavior_moves"), "Tenant should not own behavior movement state")
	assert_false(tenant_source.contains("睡觉"), "Tenant behavior labels should not be hard-coded in script")
	assert_false(need_bubble_scene.contains("bubble_text_by_behavior = {"), "NeedBubble should use scene-authored icon nodes instead of exported text dictionaries")
	assert_false(need_bubble_source.contains("@export"), "NeedBubble should not require script-level exported bubble text configuration")
	assert_false(need_bubble_source.contains("BEHAVIOR_ICON_NODE"), "NeedBubble behavior icon bindings should stay in scene metadata")
	assert_false(need_bubble_source.contains("BUBBLE_ANIMATION"), "NeedBubble animation selection should stay on the AnimatedSprite2D node")
	assert_false(need_bubble_source.contains("get_animation_names"), "NeedBubble should not choose a fallback animation")
	assert_false(need_bubble_source.contains("睡觉"), "NeedBubble should not keep display behavior names in script")
	assert_false(need_bubble_source.contains("学习/工作"), "NeedBubble display text should stay in NeedBubble.tscn")
	assert_false(emote_scene.contains("[node name=\"TenantEmote\" type=\"Label\"]"), "TenantEmote should not be a text-only label scene")
	assert_false(emote_source.contains("extends Label"), "TenantEmote should not render text directly")
	assert_false(emote_source.contains("@export"), "TenantEmote should not require script-level exported visual configuration")
	assert_false(emote_source.contains("EMOTE_ICON_NODE"), "TenantEmote icon bindings should stay in scene metadata")
	assert_false(emote_source.contains("EMOTE_ANIMATION"), "TenantEmote animation selection should stay on the AnimatedSprite2D node")
	assert_false(emote_source.contains("get_animation_names"), "TenantEmote should not choose a fallback animation")
	assert_false(room_source.contains("set_avatar_scale"), "Room should only position tenant scenes, not rewrite their internal visual layout")
	assert_false(room_source.contains("tenant_offset"), "Room should not keep naked tenant spawn coordinates")
	assert_false(room_source.contains("Marker2D"), "Room should not use scene anchors for tenant AI positions")
	assert_false(room_source.contains("tenant_view.position ="), "Room should not own tenant positioning beyond instantiation")
	assert_false(room_source.contains("func _tenant_position"), "Room should not own tenant positioning beyond instantiation")
	assert_false(room_source.contains("clampf(tenant_offset"), "Room should not clamp tenant movement against room bounds")
	assert_false(room_source.contains("room_pixel_size.y - 48.0"), "Room should not clamp CharacterBody2D tenants as if they were top-left Control previews")
	assert_false(room_source.contains("room_pixel_size.y - 4.0"), "Room should not leave CharacterBody2D tenants hovering above the floor")
	assert_false(main_source.contains("tenant_ai_timer"), "Main should not run global tenant AI ticks")
	assert_false(main_source.contains("_tick_tenant_ai"), "Main should not own tenant AI behavior selection")
	assert_false(main_source.contains("func _ready() -> void:\n\t_connect_events()\n\t_refresh_all()"), "Main should wait for state_loaded before the first building refresh")
	assert_true(main_source.contains("state_loaded_once"), "Main should gate building refresh events until save loading finishes")
	assert_true(main_source.contains("GameEvents.state_loaded.connect(_on_state_loaded)"), "Main should route loaded-state refresh through state_loaded")
	assert_true(main_source.contains("func _on_state_loaded()"), "Main should own loaded-state refresh")
	assert_true(main_source.contains("func _on_state_loaded() -> void:\n\tstate_loaded_once = true\n\t_refresh_all()"), "Main should refresh loaded state without opening a startup offscreen entry window")
	assert_false(main_source.contains("TenantAI.begin_startup_entry_refresh"), "Main should not trigger startup offscreen entry routing")
	assert_false(main_source.contains("TenantAI.end_startup_entry_refresh"), "Main should not trigger startup offscreen entry routing")
	assert_true(main_source.contains("func _refresh_building_if_loaded()"), "Main should ignore building rebuild events emitted during save normalization")
	assert_false(main_source.contains("_on_rent_changed(_value: float) -> void:\n\t_refresh_top_bar()\n\t_refresh_building()"), "Rent changes should not rebuild rooms and reset TenantAI state")
	assert_false(need_bubble_source.contains("mouse_filter ="), "NeedBubble fixed interaction settings should stay in NeedBubble.tscn")
	assert_false(emote_source.contains("mouse_filter ="), "TenantEmote fixed interaction settings should stay in TenantEmote.tscn")


func test_tenant_room_locator_uses_continuous_floor_line_positions() -> void:
	var locator_source := FileAccess.get_file_as_string("res://scripts/tenant/TenantRoomLocator.gd")
	var room := {
		"id": "__tenant_locator_test",
		"frame_tiles": [6, 4],
		"grid_size": [6, 4],
		"door_side": "left",
		"furniture_instances": []
	}
	assert_true(locator_source.contains("static func floor_y"), "TenantRoomLocator should expose floor-line y calculation")
	assert_true(locator_source.contains("static func floor_position_at_x"), "TenantRoomLocator should expose continuous floor-line positions")
	assert_true(locator_source.contains("static func spawn_position"), "TenantRoomLocator should expose spawn position generation")
	assert_true(locator_source.contains("stable_key"), "TenantRoomLocator should support stable per-tenant spawn distribution")
	assert_true(locator_source.contains("static func wander_target_position"), "TenantRoomLocator should expose floor-line wander target generation")
	assert_true(locator_source.contains("static func furniture_use_position"), "TenantRoomLocator should expose furniture-derived use positions")
	assert_true(locator_source.contains("static func room_door_inside_position"), "TenantRoomLocator should expose the room-door route position")
	assert_true(locator_source.contains("bounds_rect_for_anchor"), "Furniture use positions should use continuous furniture bounds")
	assert_false(locator_source.contains("standing_grids"), "TenantRoomLocator should not model legal standing grids")
	assert_false(locator_source.contains("static func walk_grids"), "TenantRoomLocator should not expose patrol grids")
	assert_false(locator_source.contains("static func interaction_grid"), "TenantRoomLocator should not expose furniture interaction grids")
	assert_false(locator_source.contains("static func room_door_inside_grid"), "TenantRoomLocator should not expose door route grids")

	var floor_rect := TenantRoomLocator.floor_rect(room)
	var door_route_position: Vector2 = TenantRoomLocator.room_door_inside_position(room)
	assert_eq(floor_rect, Rect2(0.0, 0.0, 96.0, 64.0), "Tenant floor line should derive from the room frame pixels")
	assert_eq(TenantRoomLocator.floor_y(room), 64.0, "Tenant floor y should be the room floor baseline")
	assert_eq(TenantRoomLocator.floor_position_at_x(room, -100.0), Vector2(4.0, 64.0), "Floor-line positions should clamp to the left visible room edge")
	assert_eq(TenantRoomLocator.floor_position_at_x(room, 999.0), Vector2(92.0, 64.0), "Floor-line positions should clamp to the right visible room edge")
	assert_eq(door_route_position, Vector2(4.0, 64.0), "Left-door rooms should route to the left end of the floor line")
	room["door_side"] = "right"
	assert_eq(TenantRoomLocator.room_door_inside_position(room), Vector2(92.0, 64.0), "Right-door rooms should route to the right end of the floor line")
	room["door_side"] = "left"
	var spawn := TenantRoomLocator.spawn_position(room, "tenant_student_01")
	assert_eq(spawn.y, 64.0, "Stable tenant spawn should stay on the floor line")
	assert_true(spawn.x >= 4.0 and spawn.x <= 92.0, "Stable tenant spawn should stay within the room width")
	assert_eq(TenantRoomLocator.wander_target_position(room, Vector2(4.0, 64.0)), Vector2(92.0, 64.0), "Floor-line wander should choose the far visible room edge")
	assert_eq(TenantRoomLocator.wander_target_position(room, Vector2(92.0, 64.0)), Vector2(4.0, 64.0), "Floor-line wander should switch back across the room")

	room["furniture_instances"] = [
		{"instance_id": "bed_a", "furniture_id": "bed_basic", "anchor_pos": [8.0, 64.0], "orientation": "default"}
	]
	var bed_data := _furniture_data("bed_basic")
	var bed_instance: Dictionary = room["furniture_instances"][0]
	var use_position := TenantRoomLocator.furniture_use_position(room, bed_instance, bed_data)
	assert_eq(use_position.y, 64.0, "Furniture use position should remain on the floor line")
	assert_true(use_position.x >= 4.0 and use_position.x <= 92.0, "Furniture use position should stay inside the room width")
	assert_true(use_position != Vector2.ZERO, "Furniture use position should not use origin as a fallback")


func test_tenant_presence_state_is_saved_and_normalized() -> void:
	var ai_source := FileAccess.get_file_as_string("res://scripts/tenant/TenantAI.gd")
	var game_state_source := FileAccess.get_file_as_string("res://scripts/autoload/GameState.gd")
	var events_source := FileAccess.get_file_as_string("res://scripts/autoload/GameEvents.gd")
	var config_source := FileAccess.get_file_as_string("res://scripts/autoload/ConfigManager.gd")
	assert_true(game_state_source.contains("TENANT_PRESENCE_HOME := \"home\""), "GameState should define a home presence state")
	assert_true(game_state_source.contains("TENANT_PRESENCE_LEAVING := \"leaving\""), "GameState should define a leaving presence state")
	assert_true(game_state_source.contains("TENANT_PRESENCE_AWAY := \"away\""), "GameState should define an away presence state")
	assert_true(game_state_source.contains("TENANT_PRESENCE_RETURNING := \"returning\""), "GameState should define a returning presence state")
	assert_true(game_state_source.contains("\"presence_state\": TENANT_PRESENCE_HOME"), "New tenant saves should default to home presence")
	assert_true(game_state_source.contains("\"away_until_timestamp\": 0"), "New tenant saves should default away timestamp")
	assert_true(game_state_source.contains("\"presence_target_room_id\": \"\""), "New tenant saves should reserve target room routing")
	assert_true(game_state_source.contains("func set_tenant_presence"), "GameState should expose presence syncing")
	assert_false(game_state_source.contains("save_needs_writeback"), "Presence state should use the current save schema without migration writeback flags")
	assert_true(events_source.contains("signal tenant_presence_changed"), "Presence changes should emit a dedicated event")
	assert_true(config_source.contains("func get_tenant_ai_value"), "Tenant AI tuning should be read from economy config")
	assert_true(economy.has("tenant_ai"), "Economy config should include tenant AI tuning")
	var ai_config: Dictionary = economy.get("tenant_ai", {})
	assert_true(ai_config.has("away_chance"), "Tenant AI config should include away chance")
	assert_true(ai_config.has("away_seconds"), "Tenant AI config should include away duration")
	assert_true(ai_config.has("return_stagger_seconds"), "Tenant AI config should include return stagger duration")
	assert_true(ai_config.has("route_speed"), "Tenant AI config should include route speed")
	assert_false(ai_config.has("entry_from_offscreen"), "Tenant AI config should not include startup offscreen entry toggling")
	assert_true(ai_config.has("door_animation_seconds"), "Tenant AI config should include door animation wait")
	assert_true(ai_config.has("door_open_idle_seconds"), "Tenant AI config should include open-door idle timing")
	assert_true(ai_config.has("elevator_animation_seconds"), "Tenant AI config should include elevator animation wait")
	assert_true(ai_config.has("elevator_idle_seconds"), "Tenant AI config should include elevator open idle timing")
	assert_true(ai_config.has("elevator_open_show_progress"), "Tenant AI config should include target elevator show progress")
	assert_true(ai_config.has("elevator_close_hide_progress"), "Tenant AI config should include source elevator hide progress")
	assert_true(ai_config.has("offscreen_margin"), "Tenant AI config should include offscreen route margin")
	assert_eq(float(ai_config.get("door_animation_seconds", 0.0)), 0.24, "Tenant doors should use the readable configured open/close duration")
	assert_eq(float(ai_config.get("door_open_idle_seconds", 0.0)), 0.12, "Tenant doors should wait briefly only after opening")
	assert_eq(float(ai_config.get("elevator_animation_seconds", 0.0)), 0.56, "Five-frame elevator doors should play near their natural duration")
	assert_eq(float(ai_config.get("elevator_idle_seconds", 0.0)), 0.25, "Elevators should wait briefly while fully open")
	assert_eq(float(ai_config.get("elevator_open_show_progress", 0.0)), 0.75, "Returning tenants should appear before the elevator is fully open")
	assert_eq(float(ai_config.get("elevator_close_hide_progress", 0.0)), 0.85, "Leaving tenants should disappear before the elevator is fully closed")
	assert_eq(float(ai_config.get("return_stagger_seconds", 0.0)), 4.0, "Tenants should stagger their return starts so they do not overlap perfectly")
	assert_eq(float(ai_config.get("offscreen_margin", 0.0)), 64.0, "Tenant offscreen route mark should sit well outside the visible left edge")
	assert_true(ai_source.contains("_staggered_away_until(away_seconds)"), "Leaving tenants should save staggered return timestamps")
	assert_true(ai_source.contains("func _return_start_delay_seconds"), "Returning tenants restored from save should stagger route start times")
	assert_true(ai_source.contains("func _tenant_return_order_index"), "Return staggering should be stable per tenant id")
	assert_true(ai_source.contains("if str(tenant_state.get(\"room_id\", \"\")).is_empty():"), "Return staggering should only count tenants who are living in rooms")
	assert_true(game_state_source.contains("\"tenants\": tenants"), "Tenant presence fields should be included in save data")
	assert_true(game_state_source.contains("_save_validation_error"), "Loaded saves should be validated before current schema state is accepted")
	assert_false(game_state_source.contains("_ensure_runtime_defaults"), "Loaded saves should not normalize legacy tenant presence fields")
	assert_false(game_state_source.contains("TENANT_PRESENCE_AWAY and int(tenant[\"away_until_timestamp\"]) <= TimeManager.now_unix()"), "Expired away presence should not be migrated during load")
	assert_false(game_state_source.contains("tenant[\"presence_state\"] = TENANT_PRESENCE_RETURNING"), "Leaving or expired away presence should not be rewritten during load")
	assert_true(game_state_source.contains("if presence == TENANT_PRESENCE_HOME:"), "Home presence should clear route-only fields")
	assert_true(game_state_source.contains("tenant[\"away_until_timestamp\"] = 0"), "Home or unassigned tenants should clear away timestamp")
	assert_true(game_state_source.contains("tenant[\"presence_target_room_id\"] = \"\""), "Home or unassigned tenants should clear target room")


func test_tenant_behavior_state_uses_keys_with_alias_config() -> void:
	var game_state_source := FileAccess.get_file_as_string("res://scripts/autoload/GameState.gd")
	var main_source := FileAccess.get_file_as_string("res://scenes/main/Main.gd")
	var config_source := FileAccess.get_file_as_string("res://scripts/autoload/ConfigManager.gd")
	var alias_config := FileAccess.get_file_as_string("res://data/behavior_aliases.json")
	assert_true(config_source.contains("behavior_aliases"), "ConfigManager should load behavior aliases for old save compatibility")
	assert_true(alias_config.contains("\"睡觉\": \"sleep\""), "Behavior aliases should migrate old display labels to behavior keys")
	assert_true(game_state_source.contains("DEFAULT_TENANT_BEHAVIOR := \"wander\""), "GameState should store behavior keys, not display labels")
	assert_true(game_state_source.contains("_need_to_behavior_key"), "Need updates should resolve to behavior keys")
	assert_true(game_state_source.contains("func set_tenant_behavior"), "GameState should expose ordinary tenant behavior syncing for TenantAI")
	assert_true(game_state_source.contains("tenant_behavior_changed.emit"), "Ordinary behavior changes should emit a visual refresh signal")
	assert_false(main_source.contains("GameState.IDLE_TENANT_BEHAVIOR"), "Main should not choose tenant behavior keys after TenantAI owns behavior selection")
	assert_false(game_state_source.contains("\"闲逛\""), "GameState should not hard-code display behavior labels")
	assert_false(game_state_source.contains("\"入住\""), "GameState should not hard-code recruited display labels")
	assert_false(main_source.contains("\"发呆\""), "Main should not write display behavior labels into state")
