@tool
extends "res://tests/support/TestSuiteBase.gd"

func suite_name() -> String:
	return "building_visuals"

func test_building_traffic_scenes_support_short_away_routes() -> void:
	var room_shell_scene := FileAccess.get_file_as_string("res://scenes/building/RoomShell.tscn")
	var room_shell_source := FileAccess.get_file_as_string("res://scripts/building/RoomShell.gd")
	var room_source := FileAccess.get_file_as_string("res://scripts/building/Room.gd")
	var service_scene := FileAccess.get_file_as_string("res://scenes/building/FloorServiceCore.tscn")
	var service_source := FileAccess.get_file_as_string("res://scripts/building/FloorServiceCore.gd")
	var public_area_scene := FileAccess.get_file_as_string("res://scenes/building/PublicAreaShell.tscn")
	var public_area_source := FileAccess.get_file_as_string("res://scripts/building/PublicAreaShell.gd")
	var floor_source := FileAccess.get_file_as_string("res://scripts/building/Floor.gd")
	var apartment_source := FileAccess.get_file_as_string("res://scripts/building/ApartmentBuilding.gd")
	var tilemap_source := FileAccess.get_file_as_string("res://scripts/building/ApartmentTileMap.gd")
	var building_view_scene := FileAccess.get_file_as_string("res://scenes/building/BuildingView.tscn")
	var building_view_source := FileAccess.get_file_as_string("res://scripts/building/BuildingView.gd")
	var ai_source := FileAccess.get_file_as_string("res://scripts/tenant/TenantAI.gd")
	var traffic_source := FileAccess.get_file_as_string("res://scripts/building/TrafficDoor.gd")
	var room_door_scene := FileAccess.get_file_as_string("res://scenes/building/RoomDoor.tscn")
	var exit_door_scene := FileAccess.get_file_as_string("res://scenes/building/ExitDoor.tscn")
	var elevator_door_scene := FileAccess.get_file_as_string("res://scenes/building/ElevatorDoor.tscn")
	var ai_config: Dictionary = economy.get("tenant_ai", {})
	assert_true(room_shell_scene.contains("res://scenes/building/RoomDoor.tscn"), "RoomShell should overlay a reusable room door scene")
	assert_true(room_shell_scene.contains("[node name=\"RoomDoor\""), "RoomShell should expose a RoomDoor child")
	assert_true(room_shell_source.contains("func get_room_door()"), "RoomShell should expose the room door to route scripts")
	assert_true(room_shell_source.contains("door_mirrored"), "RoomShell should support mirrored outward-opening room doors")
	assert_true(room_shell_source.contains("normalized_side == \"right\""), "RoomShell should support right-wall room doors")
	assert_true(room_shell_source.contains("-ApartmentTileMap.TILE_SIZE * 0.5"), "Left-wall room doors should sit outside the room wall")
	assert_true(room_shell_source.contains("room_pixel_size.x + ApartmentTileMap.TILE_SIZE * 0.5"), "Right-wall room doors should sit outside the room wall")
	assert_true(room_shell_source.contains("room_door.scale.x = -1.0"), "RoomShell should flip only the right-side 02 door instances")
	assert_true(room_source.contains("clip_contents = false"), "Room buttons should not clip outward-opening room doors")
	assert_true(service_scene.contains("TrafficRoot"), "FloorServiceCore should group route traffic nodes")
	assert_true(service_scene.contains("res://scenes/building/ExitDoor.tscn"), "FloorServiceCore should keep its legacy exit-door node hidden")
	assert_true(service_scene.contains("res://scenes/building/ElevatorDoor.tscn"), "FloorServiceCore should instance the elevator door scene")
	assert_true(service_source.contains("exit_door.visible = false"), "Central elevator halls should not own the 1F entrance door")
	assert_true(service_source.contains("elevator_door.visible = true"), "Every floor service core should show an elevator door")
	assert_true(public_area_scene.contains("res://scenes/building/ExitDoor.tscn"), "1F public lobby should own the reusable exit door scene")
	assert_true(public_area_source.contains("has_entrance_door"), "Public areas should opt into a visible entrance door through floor config")
	assert_true(public_area_source.contains("door_side"), "Public entrance doors should be positioned from their configured wall side")
	assert_true(public_area_source.contains("var door_x := ApartmentTileMap.TILE_SIZE * 0.5"), "1F entrance doors should sit inside the left wall tile")
	assert_true(public_area_source.contains("area_pixel_size.x - ApartmentTileMap.TILE_SIZE * 0.5"), "Right-side public entrance doors should sit inside the right wall tile")
	assert_true(public_area_scene.contains("position = Vector2(8, 64)"), "PublicAreaShell preview should show the entrance door on the left wall tile")
	assert_true(floor_source.contains("area_view.call_deferred(\n\t\t\t\"apply_layout\""), "Public area layout should run after scene onready nodes bind")
	assert_true(floor_source.contains("_public_body_sides"), "1F public areas should suppress their shared interior walls")
	assert_true(building_view_source.contains("_public_entry_area"), "Building routes should prefer the 1F public lobby entrance over the service core")
	assert_true(service_source.contains("size.x * 0.5"), "Elevator route anchor should stay centered in the service core")
	assert_true(service_source.contains("service_width * 0.5"), "Elevator door should stay visually centered in the service core")
	assert_true(floor_source.contains("service_core.apply_layout(service_width, floor_height, floor_index, _service_edge_sides(), _service_body_sides())"), "Floor should pass floor_index and wall-outline rules into the service core")
	assert_true(service_source.contains("body_sides, \"\")"), "Central elevator halls should render without left/right door wall cutouts")
	assert_true(floor_source.contains("func _service_edge_sides"), "Floor should own service-core outer edge rules")
	assert_true(floor_source.contains("func _room_edge_sides"), "Floor should own room outer edge rules")
	assert_true(floor_source.contains("\"right\": false"), "Service core should not draw a right-side edge/body at the room join")
	assert_true(floor_source.contains("\"left\": false"), "Service core should not draw a left-side edge/body at the room join")
	assert_true(floor_source.contains("layout_side == \"left\""), "Left rooms should own the building's left outer wall")
	assert_true(floor_source.contains("layout_side == \"right\""), "Right rooms should own the building's right outer wall")
	assert_true(floor_source.contains("\"bottom\": false"), "Floor wall-edge rules should avoid top and bottom black outlines")
	assert_true(tilemap_source.contains("current_edge_sides"), "ApartmentTileMap should support per-side outer wall edge rendering")
	assert_true(tilemap_source.contains("current_body_sides"), "ApartmentTileMap should support removing duplicate service/room body walls")
	assert_true(tilemap_source.contains("edge_left_door_edge_tiles"), "ApartmentTileMap should expose a separate black left-door edge tile sequence")
	assert_true(tilemap_source.contains("body_right_door_edge_tiles"), "ApartmentTileMap should expose a separate right-wall door short-edge tile sequence")
	assert_true(tilemap_source.contains("if show_roof:"), "ApartmentTileMap should suppress top wall edge when a roof is visible")
	assert_true(apartment_source.contains("func find_floor_service_core"), "ApartmentBuilding should expose floor service cores for tenant routes")
	assert_true(building_view_scene.contains("TenantWorldLayer"), "BuildingView should expose a building-level tenant movement layer")
	assert_true(building_view_scene.contains("z_index = 20"), "TenantWorldLayer should render tenants in front of traffic doors during routes")
	assert_true(building_view_scene.contains("TenantRouteMarkers"), "BuildingView should expose editable tenant route markers")
	assert_true(building_view_scene.contains("LeftOffscreenMarker"), "BuildingView should expose a left offscreen marker for exit and entry routes")
	assert_true(building_view_source.contains("func get_tenant_world_layer"), "BuildingView should expose TenantWorldLayer to TenantAI")
	assert_true(building_view_source.contains("TenantAI.reset_startup_entry_session()"), "BuildingView should reset startup-entry tracking each time the scene starts")
	assert_false(building_view_source.contains("world_camera.make_current()\n\trefresh()"), "BuildingView should let Main own the initial building refresh to avoid rebuilding active startup-entry tenants")
	assert_true(building_view_source.contains("func get_service_exit_world_position"), "BuildingView should expose the 1F exit route anchor")
	assert_true(building_view_source.contains("func get_service_elevator_world_position"), "BuildingView should expose elevator route anchors")
	assert_true(building_view_source.contains("func get_left_offscreen_route_mark_world_position"), "BuildingView should expose a shared offscreen route mark")
	assert_true(building_view_source.contains("world_camera.position.x - _visible_world_size().x * 0.5"), "Offscreen route mark should use the current visible screen left edge")
	assert_false(building_view_source.contains("left_offscreen_marker.global_position ="), "BuildingView should not persist runtime offscreen mark coordinates into the scene")
	assert_true(building_view_source.contains("startup_entry_active := TenantAI.is_startup_entry_active"), "BuildingView should preserve world-layer startup entry tenants during HOME refreshes")
	assert_true(building_view_source.contains("not startup_entry_active"), "BuildingView should not delete an active startup entry tenant just because persisted presence is home")
	assert_true(traffic_source.contains("func play_open(duration_seconds"), "TrafficDoor should provide a duration-aware open animation hook")
	assert_true(traffic_source.contains("func play_close(duration_seconds"), "TrafficDoor should provide a duration-aware close animation hook")
	assert_true(traffic_source.contains("func set_open()"), "TrafficDoor should expose a final open-frame setter for route cleanup")
	assert_true(traffic_source.contains("func set_closed()"), "TrafficDoor should expose a final closed-frame setter for route cleanup")
	assert_true(traffic_source.contains("_custom_speed_for_duration"), "TrafficDoor should scale animation playback to the configured route timing")
	assert_true(ai_source.contains("door.play_open(duration)"), "TenantAI should pass configured door timing into TrafficDoor")
	assert_true(ai_source.contains("await _wait_seconds(duration)"), "TenantAI should wait for door/elevator timing before continuing route movement")
	assert_true(ai_source.contains("door.set_open()"), "TenantAI should force door animations onto their final open frame after waiting")
	assert_true(ai_source.contains("door.set_closed()"), "TenantAI should force door animations onto their final closed frame after waiting")
	assert_true(ai_source.contains("func _enter_elevator_at_floor"), "TenantAI should isolate source-floor elevator entry timing")
	assert_true(ai_source.contains("await _play_elevator_door(view, floor_index, true)\n\tawait _play_elevator_door(view, floor_index, false)\n\ttenant.visible = false"), "Source elevator flow should close the door before hiding the tenant")
	assert_true(ai_source.contains("func _exit_elevator_at_floor"), "TenantAI should isolate target-floor elevator exit timing")
	assert_true(ai_source.contains("await _play_elevator_door(view, floor_index, true)\n\ttenant.position = elevator_position\n\ttenant.visible = true"), "Target elevator flow should open before showing the tenant")
	assert_true(ai_source.contains("await _move_to_position(_route_step_position(elevator_position, direction))\n\tawait _play_elevator_door(view, floor_index, false)"), "Target elevator flow should let the tenant leave before closing")
	assert_eq(float(ai_config.get("door_animation_seconds", 0.0)), 0.24, "Room and exit doors should open and close slowly enough to read")
	assert_eq(float(ai_config.get("elevator_animation_seconds", 0.0)), 0.36, "Elevators should wait long enough before tenant floor transitions")
	assert_false(room_door_scene.contains("\"speed\": 1.0"), "Room door should animate quickly enough before tenants walk through")
	assert_false(exit_door_scene.contains("\"speed\": 1.0"), "Exit door should animate quickly enough before tenants walk through")
	assert_false(elevator_door_scene.contains("\"speed\": 3.0"), "Elevator door should animate quickly enough for route timing")
	for floor in floors:
		var floor_data: Dictionary = floor
		if int(floor_data.get("floor_index", 0)) <= 1:
			continue
		assert_true(str(floor_data.get("floor_icon_asset", {}).get("texture", "")).ends_with("Elevator.png"), "%dF service icon should read as an elevator, not a normal door" % int(floor_data.get("floor_index", 0)))


func test_building_outer_wall_edges_follow_floor_rules() -> void:
	var tilemap_source := FileAccess.get_file_as_string("res://scripts/building/ApartmentTileMap.gd")
	var floor_source := FileAccess.get_file_as_string("res://scripts/building/Floor.gd")
	var service_source := FileAccess.get_file_as_string("res://scripts/building/FloorServiceCore.gd")
	assert_true(tilemap_source.contains("func _edge_side_enabled"), "ApartmentTileMap should gate outer wall-edge cells per side")
	assert_true(tilemap_source.contains("func _body_side_enabled"), "ApartmentTileMap should gate ordinary wall body cells per side")
	assert_true(tilemap_source.contains("func _should_paint_body_cell"), "ApartmentTileMap should skip duplicate service-side body walls")
	assert_true(tilemap_source.contains("if show_roof:\n\t\tcurrent_edge_sides[EDGE_TOP] = false"), "Visible roof should suppress top wall edge")
	assert_true(floor_source.contains("\"left\": false"), "Central service core should not draw duplicate side edge/body walls")
	assert_true(floor_source.contains("\"right\": false"), "Central service core should not draw duplicate side edge/body walls")
	assert_true(floor_source.contains("layout_side == \"left\""), "Left rooms should draw the building left edge")
	assert_true(floor_source.contains("layout_side == \"right\""), "Right rooms should draw the building right edge")
	assert_true(floor_source.contains("\"right\": layout_side != \"left\""), "Left 1F public area should not draw the interior right wall")
	assert_true(floor_source.contains("\"left\": layout_side != \"right\""), "Right 1F public area should not draw the interior left wall")
	assert_true(floor_source.contains("\"bottom\": false"), "Top and bottom black wall edges should stay disabled")
	assert_true(service_source.contains("exit_door.visible = false"), "Service cores should keep normal exit doors hidden on every floor")
	assert_true(service_source.contains("elevator_door.visible = true"), "All service cores should keep their elevator visible")
	var room_source := FileAccess.get_file_as_string("res://scripts/building/Room.gd")
	var tenant_scene := FileAccess.get_file_as_string("res://scenes/tenant/Tenant.tscn")
	assert_true(room_source.contains("furniture_view.z_index = 6 if layer == FurniturePlacementRules.LAYER_WALL else 8 + int(grid_pos[1])"), "Furniture should keep its per-layer z-order in rooms")
	assert_true(tenant_scene.contains("z_index = 40"), "In-room tenants should render in front of every furniture item")


func test_building_view_uses_backgrounds_atlas_for_scene_backdrop() -> void:
	var building_scene := FileAccess.get_file_as_string("res://scenes/building/BuildingView.tscn")
	var backdrop_scene := FileAccess.get_file_as_string("res://scenes/building/SceneBackdrop.tscn")
	var backdrop_source := FileAccess.get_file_as_string("res://scripts/building/SceneBackdrop.gd")
	var tileset_source := FileAccess.get_file_as_string("res://tilesets/background_tileset.tres")
	var tileset := ResourceLoader.load("res://tilesets/background_tileset.tres") as TileSet
	var atlas_source := tileset.get_source(0) as TileSetAtlasSource
	assert_true(building_scene.contains("res://scenes/building/SceneBackdrop.tscn"), "BuildingView should instance the independent backdrop scene")
	assert_true(building_scene.contains("res://scenes/building/ApartmentBuilding.tscn"), "BuildingView should instance the independent apartment scene")
	assert_true(backdrop_scene.contains("Backgrounds.png"), "Backdrop nodes should draw from Pixel Spaces Backgrounds.png")
	assert_true(backdrop_scene.contains("res://tilesets/background_tileset.tres"), "Backdrop TileMapLayers should share the internal background TileSet resource")
	assert_true(tileset_source.contains("res://assets/pixel_spaces/tileset/Backgrounds.png"), "Background TileSet should reference the external Pixel Spaces texture")
	assert_eq(tileset.tile_size, Vector2i(16, 16), "Background TileSet should use 16x16 tile cells")
	assert_eq(atlas_source.texture_region_size, Vector2i(16, 16), "Background atlas source should use 16x16 atlas cells")
	assert_false(tileset_source.contains("tile_size = Vector2i(1, 1)"), "Background TileSet should not use 1x1 tiles")
	assert_false(tileset_source.contains("tile_size = Vector2i(42, 32)"), "Background TileSet should not use non-grid tile sizes")
	assert_false(tileset_source.contains("texture_region_size = Vector2i(1, 1)"), "Background atlas source should not use 1x1 atlas regions")
	assert_false(tileset_source.contains("texture_region_size = Vector2i(42, 32)"), "Background atlas source should not use non-grid atlas regions")
	assert_false(tileset_source.contains("texture_region_size = Vector2i(16, 112)"), "Sky slice should not be stored as the TileSet atlas region size")
	assert_true(tileset_source.contains("size_in_atlas"), "Background TileSet should preserve the configured multi-cell atlas tiles")
	assert_true(backdrop_scene.contains("Cloud_01"), "Cloud sprites should be editor-authored children, not generated by SceneBackdrop")
	assert_true(backdrop_scene.contains("repeat_size = Vector2(360, 0)"), "Cloud parallax should repeat horizontally on the 360px design canvas")
	assert_true(backdrop_scene.contains("scale = Vector2(1.5, 1.5)"), "Cloud scale should be authored in the scene for the 360x640 design canvas")
	for node_name in ["WorldClip", "WorldViewport", "WorldRoot", "SceneBackdrop", "ApartmentBuilding", "WorldCamera"]:
		assert_true(building_scene.contains("name=\"%s\"" % node_name), "BuildingView should expose %s in the editable scene tree" % node_name)
	for node_name in ["SkySprite", "Tiles", "MountainTileMap", "BackgroundBuildingTileMap", "TreeTileMap", "GroundTileMap", "CloudParallax"]:
		assert_true(backdrop_scene.contains("name=\"%s\"" % node_name), "SceneBackdrop should expose %s in the editable scene tree" % node_name)
	assert_true(backdrop_scene.contains("type=\"TileMapLayer\""), "Backdrop scenery should be built with TileMapLayer nodes")
	assert_true(backdrop_scene.contains("type=\"Sprite2D\""), "Sky should be a stretched Sprite2D because the source sky is not tilemap-friendly")
	assert_true(backdrop_scene.contains("type=\"Parallax2D\""), "Clouds should live in a Parallax2D node")
	assert_false(building_scene.contains("ViewportSkyFill"), "BuildingView should not hide map gaps with a viewport fill node")
	assert_false(building_scene.contains("GroundColor"), "Ground should be a tile layer, not a fallback ColorRect")
	assert_false(building_scene.contains("SkyBackground"), "BuildingView should not use a flat sky ColorRect fallback")
	assert_false(building_scene.contains("GroundBand"), "BuildingView should not use a flat ground ColorRect fallback")
	assert_false(backdrop_scene.contains("AtlasTexture_"), "SceneBackdrop should not store per-slice AtlasTexture resources")
	assert_false(backdrop_scene.contains("TileSetAtlasSource_"), "SceneBackdrop should not embed generated TileSet atlas sources")
	assert_false(backdrop_scene.contains("scroll_offset"), "SceneBackdrop should not persist runtime cloud drift")
	assert_false(backdrop_scene.contains("GrassDetailTileMap"), "Ground should stay to the single bottom TileMapLayer")
	assert_false(backdrop_source.contains("@tool"), "Backdrop should not run editor-time generation over manual TileMap edits")
	assert_false(backdrop_source.contains("@export"), "Backdrop should read scene-authored config instead of script exports")
	assert_false(backdrop_source.contains("TileSet.new"), "Backdrop should not create TileSets at runtime")
	assert_false(backdrop_source.contains("TileSetAtlasSource.new"), "Backdrop should not slice atlas sources at runtime")
	assert_false(backdrop_source.contains("set_cell"), "Backdrop should not paint TileMap cells at runtime")
	assert_false(backdrop_source.contains(".clear()"), "Backdrop should not clear manually painted TileMap cells at runtime")
	assert_false(backdrop_source.contains("set_map_size"), "Backdrop coverage should come from the project viewport and editable scene nodes")
	assert_false(backdrop_source.contains("map_size"), "Backdrop should not resize editor-authored sky or TileMap layers at runtime")
	assert_false(backdrop_source.contains("_apply_sky"), "SkySprite should be configured in the editor")
	assert_false(backdrop_source.contains("_rebuild_clouds"), "Cloud sprites should be configured in the editor")
	assert_false(backdrop_source.contains("Sprite2D.new"), "SceneBackdrop should not generate cloud sprites at runtime")
	assert_false(backdrop_source.contains("scroll_offset"), "SceneBackdrop should not drift manually positioned clouds into the ground")
	assert_false(backdrop_source.contains("_paint_tile_layers"), "Backdrop should not auto-generate scenery TileMap layers")
	assert_false(backdrop_source.contains("auto_generate_tilemaps"), "Backdrop should leave all TileMap painting to the editor")
	assert_false(backdrop_source.contains("get_tile_size_in_atlas"), "Backdrop should not inspect atlas stamps for runtime placement")
	assert_false(backdrop_source.contains("sky_tile_texture"), "Sky should use a simple region on SkySprite instead of exported AtlasTexture slices")
	assert_false(backdrop_source.contains("ground_tile_texture"), "Ground should use shared TileSet atlas coordinates")
	assert_false(backdrop_source.contains("mountain_scale"), "Backdrop should not scale TileMap scenery layers")
	assert_false(backdrop_source.contains("layer.scale"), "Backdrop should not adjust TileMapLayer scale")
	assert_false(backdrop_source.contains("layer.position"), "Backdrop should not adjust TileMapLayer position")
	assert_false(backdrop_source.contains("@export var cloud_slices"), "Backdrop should not hide atlas slices in script arrays")
	assert_false(backdrop_source.contains("draw_texture_rect"), "Backdrop should not custom-draw atlas layers")
	assert_true(backdrop_source.contains("ground_rows"), "Ground should be constrained to at most three 16px rows")


func test_floor_and_room_visuals_use_building_atlases() -> void:
	var floor_source := FileAccess.get_file_as_string("res://scripts/building/Floor.gd")
	var service_source := FileAccess.get_file_as_string("res://scripts/building/FloorServiceCore.gd")
	var room_source := FileAccess.get_file_as_string("res://scripts/building/Room.gd")
	var floor_scene := FileAccess.get_file_as_string("res://scenes/building/Floor.tscn")
	var floor_service_scene := FileAccess.get_file_as_string("res://scenes/building/FloorServiceCore.tscn")
	var service_tilemap_scene := FileAccess.get_file_as_string("res://scenes/building/ServiceCoreTileMap.tscn")
	var room_scene := FileAccess.get_file_as_string("res://scenes/building/Room.tscn")
	var room_shell_scene := FileAccess.get_file_as_string("res://scenes/building/RoomShell.tscn")
	var room_shell_source := FileAccess.get_file_as_string("res://scripts/building/RoomShell.gd")
	var apartment_tilemap_scene := FileAccess.get_file_as_string("res://scenes/building/ApartmentTileMap.tscn")
	var apartment_tilemap_source := FileAccess.get_file_as_string("res://scripts/building/ApartmentTileMap.gd")
	var apartment_tileset_source := FileAccess.get_file_as_string("res://tilesets/apartment_tileset.tres")
	var apartment_tileset := ResourceLoader.load("res://tilesets/apartment_tileset.tres", "", ResourceLoader.CACHE_MODE_REPLACE) as TileSet
	var floor_counts := {}
	for room in rooms:
		var room_data: Dictionary = room
		var floor_index := int(room_data.get("floor_index", 0))
		var frame_tiles: Array = room_data.get("frame_tiles", [])
		var grid_size: Array = room_data.get("grid_size", [])
		floor_counts[floor_index] = int(floor_counts.get(floor_index, 0)) + 1
		assert_true(ResourceLoader.exists(str(room_data.get("room_scene_path", ""))), "%s should configure a loadable room scene template" % room_data.get("id", ""))
		assert_true(_asset_texture_exists(room_data.get("infrastructure_asset", {})), "%s should use Infrastructure.png for its room frame" % room_data.get("id", ""))
		assert_true(_asset_texture_exists(room_data.get("wall_asset", {})), "%s wallpaper asset should exist" % room_data.get("id", ""))
		assert_false(room_data.has("floor_asset"), "%s should not keep a separate floor layer asset for room skeletons" % room_data.get("id", ""))
		assert_false(room_data.has("room_size"), "%s should not keep legacy pixel room_size config" % room_data.get("id", ""))
		assert_false(room_data.has("grid_rect"), "%s should not keep legacy pixel grid_rect config" % room_data.get("id", ""))
		assert_eq(frame_tiles.size(), 2, "%s should configure frame_tiles as [width, height]" % room_data.get("id", ""))
		assert_eq(grid_size.size(), 2, "%s should configure grid_size as [width, height]" % room_data.get("id", ""))
		assert_true(room_data.has("layout_side"), "%s should declare its side relative to the central elevator" % room_data.get("id", ""))
		assert_true(room_data.has("door_side"), "%s should declare which wall owns its outward door" % room_data.get("id", ""))
		assert_true(room_data.has("door_mirrored"), "%s should declare whether its door scene is mirrored" % room_data.get("id", ""))
		if frame_tiles.size() >= 2 and grid_size.size() >= 2:
			assert_eq(int(frame_tiles[0]), 6, "%s should start as a 6-tile-wide room frame" % room_data.get("id", ""))
			assert_eq(int(frame_tiles[1]), 4, "%s room frame height should stay fixed at 4 tiles" % room_data.get("id", ""))
			assert_eq(int(grid_size[0]), int(frame_tiles[0]), "%s placement grid width should use the full room frame" % room_data.get("id", ""))
			assert_eq(int(grid_size[1]), int(frame_tiles[1]), "%s floor placement grid height should match the 4-tile room height" % room_data.get("id", ""))
		if str(room_data.get("id", "")).ends_with("01"):
			assert_eq(str(room_data.get("layout_side", "")), "left", "%s should sit left of the elevator" % room_data.get("id", ""))
			assert_eq(str(room_data.get("door_side", "")), "right", "%s should put its door on the right wall" % room_data.get("id", ""))
			assert_false(bool(room_data.get("door_mirrored", true)), "%s should use the existing door scene orientation" % room_data.get("id", ""))
		if str(room_data.get("id", "")).ends_with("02"):
			assert_eq(str(room_data.get("layout_side", "")), "right", "%s should sit right of the elevator" % room_data.get("id", ""))
			assert_eq(str(room_data.get("door_side", "")), "left", "%s should put its door on the left wall" % room_data.get("id", ""))
			assert_true(bool(room_data.get("door_mirrored", false)), "%s should mirror the reusable door scene" % room_data.get("id", ""))
		for item in room_data.get("layout_upgrades", []):
			var upgrade: Dictionary = item
			var upgraded_frame_tiles: Array = upgrade.get("frame_tiles", [])
			var upgraded_grid_size: Array = upgrade.get("grid_size", [])
			assert_eq(upgraded_frame_tiles.size(), 2, "%s layout upgrade should configure frame_tiles" % room_data.get("id", ""))
			assert_eq(upgraded_grid_size.size(), 2, "%s layout upgrade should configure grid_size" % room_data.get("id", ""))
			if upgraded_frame_tiles.size() >= 2 and upgraded_grid_size.size() >= 2 and frame_tiles.size() >= 2 and grid_size.size() >= 2:
				assert_gt(int(upgraded_frame_tiles[0]), int(frame_tiles[0]), "%s layout upgrades should add width tiles" % room_data.get("id", ""))
				assert_eq(int(upgraded_frame_tiles[1]), int(frame_tiles[1]), "%s layout upgrades should not change room height" % room_data.get("id", ""))
				assert_gt(int(upgraded_grid_size[0]), int(grid_size[0]), "%s layout upgrades should add placement columns" % room_data.get("id", ""))
				assert_eq(int(upgraded_grid_size[1]), int(grid_size[1]), "%s layout upgrades should not change floor placement rows" % room_data.get("id", ""))
	assert_false(floor_counts.has(1), "1F should not configure rentable rooms")
	for floor_index in floor_counts.keys():
		assert_eq(int(floor_counts[floor_index]), 2, "%dF should have two rooms around the elevator" % int(floor_index))
	assert_eq(_room_ids_on_floor(2), ["room_201", "room_202"], "2F should configure 201/202 around the elevator")
	assert_eq(_room_ids_on_floor(3), ["room_301", "room_302"], "3F should configure 301/302 around the elevator")
	assert_true(floor_scene.contains("FloorServiceCore.tscn"), "Each floor should expose a central elevator service core scene")
	assert_true(floor_scene.contains("PublicAreaShell.tscn"), "1F should configure visual-only public area shells")
	assert_true(floor_scene.contains("[node name=\"SceneConfig\" type=\"Node\""), "Floor should keep room template config in Floor.tscn")
	assert_true(floor_scene.contains("metadata/room_scene_path = \"res://scenes/building/Room.tscn\""), "Floor should assign the editable Room template in scene metadata")
	assert_true(floor_service_scene.contains("ServiceCoreTileMap.tscn"), "FloorServiceCore should compose an editable TileMap template")
	assert_true(service_tilemap_scene.contains("res://tilesets/apartment_tileset.tres"), "ServiceCoreTileMap should share the internal apartment TileSet")
	for layer_name in ["WallpaperTileMap", "WallTileMap", "InfrastructureTileMap", "RoofTileMap", "ConstructionTileMap"]:
		assert_true(service_tilemap_scene.contains("name=\"%s\" type=\"TileMapLayer\"" % layer_name), "ServiceCoreTileMap should expose %s for editor painting" % layer_name)
	assert_false(service_tilemap_scene.contains("name=\"FloorTileMap\""), "ServiceCoreTileMap should not keep a separate floor layer")
	assert_true(floor_service_scene.contains("FloorLabel"), "FloorServiceCore should expose its floor label in the scene")
	assert_true(floor_service_scene.contains("theme_override_font_sizes/font_size = 9"), "Floor label style should be editor-authored")
	assert_true(floor_source.contains("get_node_or_null(\"FloorServiceCore\")"), "Floor should bind the scene-authored service core node")
	assert_true(floor_source.contains("room_scene_path"), "Floor should allow room config to select an editor-authored room scene template")
	assert_true(floor_source.contains("_scene_from_path"), "Floor should load configured room templates with scene default fallback")
	assert_false(floor_source.contains("FLOOR_SERVICE_CORE_SCENE"), "Floor should not instantiate the service-core scene as a fallback")
	assert_false(floor_source.contains("preload(\"res://scenes/building/Room.tscn\")"), "Floor should not hide the room template in script")
	assert_false(floor_source.contains("@export"), "Floor should read scene-authored config instead of script exports")
	assert_false(floor_source.contains("apply_asset_to_texture_rect"), "Floor service-core visuals should be editor-painted TileMaps")
	assert_false(floor_source.contains("AtlasTexture.new"), "Floor should not create atlas slices for service-core visuals")
	assert_false(service_source.contains("TextureRect"), "FloorServiceCore should not depend on scripted texture slices")
	assert_false(service_source.contains("ColorRect"), "FloorServiceCore should not depend on scripted color fallbacks")
	assert_false(service_source.contains("add_theme_"), "FloorServiceCore should not hide fixed label styling in script")
	assert_true(room_scene.contains("RoomShell.tscn"), "Room should compose its editable shell scene")
	assert_true(room_scene.contains("[node name=\"SceneConfig\" type=\"Node\""), "Room should keep child template and layout config in Room.tscn")
	assert_true(room_scene.contains("metadata/tenant_scene_path = \"res://scenes/tenant/Tenant.tscn\""), "Room should assign the editable tenant child scene in scene metadata")
	assert_true(room_scene.contains("metadata/furniture_scene_path = \"res://scenes/furniture/Furniture.tscn\""), "Room should assign the editable furniture child scene in scene metadata")
	assert_true(room_scene.contains("StyleBoxFlat_room_normal"), "Room button skin should be editor-authored")
	assert_true(room_scene.contains("[node name=\"TemplateText\" type=\"Control\""), "Room display text templates should be authored in Room.tscn")
	assert_true(room_scene.contains("[node name=\"FallbackRoomName\" type=\"Label\""), "Room fallback display text should be authored in Room.tscn")
	assert_true(room_scene.contains("[node name=\"RentBadgeTemplate\" type=\"Label\""), "Room rent badge template should be authored in Room.tscn")
	assert_true(room_shell_scene.contains("ApartmentTileMap.tscn"), "Room shell should compose the editable apartment TileMap template")
	assert_true(room_shell_scene.contains("text = \"房间\""), "Room name badge should be previewable in RoomShell.tscn")
	assert_true(room_shell_scene.contains("text = \"评分 0  租金 0\""), "Room rent badge should be previewable in RoomShell.tscn")
	assert_true(room_shell_scene.contains("anchor_left = 1.0"), "Room rent badge should use editor-authored right anchoring")
	assert_true(room_shell_scene.contains("theme_override_font_sizes/font_size = 9"), "Room name badge style should be editor-authored")
	assert_true(room_shell_scene.contains("theme_override_font_sizes/font_size = 8"), "Room rent badge style should be editor-authored")
	assert_true(apartment_tilemap_scene.contains("res://tilesets/apartment_tileset.tres"), "ApartmentTileMap should share the internal apartment TileSet")
	for layer_name in ["WallpaperTileMap", "WallTileMap", "InfrastructureTileMap", "RoofTileMap", "ConstructionTileMap"]:
		assert_true(apartment_tilemap_scene.contains("name=\"%s\" type=\"TileMapLayer\"" % layer_name), "ApartmentTileMap should expose %s for editor painting" % layer_name)
	assert_false(apartment_tilemap_scene.contains("name=\"FloorTileMap\""), "ApartmentTileMap should not keep a separate floor layer")
	assert_false(apartment_tilemap_scene.contains("tile_map_data"), "ApartmentTileMap scene should not save editor-painted sample tiles as runtime templates")
	assert_true(apartment_tileset != null, "Apartment TileSet should load")
	if apartment_tileset != null:
		assert_eq(apartment_tileset.tile_size, Vector2i(16, 16), "Apartment TileSet should use 16x16 tile cells")
		assert_eq(apartment_tileset.get_terrain_sets_count(), 2, "Apartment TileSet should expose two editor-visible terrain sets")
		assert_eq(apartment_tileset.get_terrain_name(0, 0), "RoomFrame", "Terrain set 0 should expose RoomFrame")
		assert_eq(apartment_tileset.get_terrain_name(1, 0), "WallpaperFill", "Terrain set 1 should expose WallpaperFill")
		assert_eq((apartment_tileset.get_source(0) as TileSetAtlasSource).texture_region_size, Vector2i(16, 16), "Infrastructure atlas source should use 16x16 atlas cells")
		var wallpaper_source := _tileset_source_with_texture(apartment_tileset, "Wallpaper Tilesets.png")
		assert_true(wallpaper_source != null, "Wallpaper atlas source should be discoverable by texture path")
		if wallpaper_source != null:
			assert_eq(wallpaper_source.texture_region_size, Vector2i(16, 16), "Wallpaper atlas source should use 16x16 atlas cells")
	assert_true(apartment_tileset_source.contains("Infrastructure.png"), "Apartment TileSet should reference the infrastructure atlas")
	assert_true(apartment_tileset_source.contains("Wallpaper Tilesets.png"), "Apartment TileSet should reference the wallpaper atlas")
	assert_true(apartment_tileset_source.contains("RoomFrame"), "Apartment TileSet should save room-frame terrain rules")
	assert_true(apartment_tileset_source.contains("WallpaperFill"), "Apartment TileSet should save wallpaper-fill terrain rules")
	assert_true(apartment_tilemap_source.contains("render_room_skeleton"), "ApartmentTileMap should be the dedicated grid renderer for room frames")
	assert_true(apartment_tilemap_source.contains("set_cell"), "ApartmentTileMap may paint generated room skeleton cells")
	assert_true(apartment_tilemap_source.contains("@export var body_top_left_corner_tile"), "ApartmentTileMap should export themed wall-body corner coordinates for editor filling")
	assert_true(apartment_tilemap_source.contains("@export var edge_top_left_corner_tile"), "ApartmentTileMap should export fixed wall-edge corner coordinates for editor filling")
	assert_true(apartment_tilemap_source.contains("@export var wallpaper_tile"), "ApartmentTileMap should export the default wallpaper tile coordinate")
	assert_true(apartment_tilemap_source.contains("@export var body_door_short_wall_cells"), "ApartmentTileMap should export body short-wall cells around doors")
	assert_true(apartment_tilemap_source.contains("@export var edge_door_short_wall_cells"), "ApartmentTileMap should export edge short-wall cells around doors")
	assert_false(apartment_tilemap_source.contains("@export var floor_tiles"), "ApartmentTileMap should not expose a separate floor layer for room skeletons")
	assert_false(apartment_tilemap_source.contains("func _paint_floor"), "ApartmentTileMap should not paint FloorTileMap for room skeletons")
	assert_false(apartment_tilemap_source.contains("func _paint_room_door"), "ApartmentTileMap should not paint room door visuals after RoomDoor owns the door")
	assert_false(apartment_tilemap_source.contains("_ensure_template_captured"), "ApartmentTileMap should not capture editor-painted samples as runtime templates")
	assert_false(apartment_tilemap_source.contains("_paint_infrastructure_template"), "ApartmentTileMap should use configured tile coordinates instead of replaying templates")
	assert_true(apartment_tilemap_source.contains("@export var window_tile"), "ApartmentTileMap should export the window tile coordinate")
	assert_true(apartment_tilemap_source.contains("@export var construction_marker_tile"), "ApartmentTileMap should export construction marker tile coordinates")
	assert_false(room_source.contains("_asset_tile_origin"), "Room should not infer TileSet atlas coordinates from asset regions")
	assert_false(room_source.contains("wallpaper_origin"), "Room should not pass guessed wallpaper atlas origins")
	assert_false(room_source.contains("frame_origin"), "Room should not pass guessed frame atlas origins")
	for path in [
		"res://scripts/building/Room.gd",
		"res://scripts/building/Floor.gd",
		"res://scripts/building/BuildSlot.gd",
		"res://scripts/building/ApartmentBuilding.gd"
	]:
		var building_source := FileAccess.get_file_as_string(path)
		assert_false(building_source.contains("set_cell"), "%s should pass frame_tiles to ApartmentTileMap instead of painting cells" % path)
	assert_false(room_source.contains("StyleBoxFlat.new"), "Room should not create fixed button skins in script")
	assert_false(room_source.contains("add_theme_"), "Room should not hide fixed badge styling in script")
	assert_false(room_source.contains("@export"), "Room should read scene-authored config instead of script exports")
	assert_false(room_source.contains("评分"), "Room should not hard-code badge copy in script")
	assert_false(room_source.contains("租金"), "Room should not hard-code badge copy in script")
	assert_false(room_source.contains("\"房间\""), "Room fallback display copy should stay in Room.tscn")
	assert_false(room_source.contains("@export var infrastructure_texture"), "Room body visuals should move to TileMap instead of inspector texture slices")
	assert_false(room_source.contains("preload(\"res://scenes/tenant/Tenant.tscn\")"), "Room should not hide tenant child templates in script")
	assert_false(room_source.contains("preload(\"res://scenes/furniture/Furniture.tscn\")"), "Room should not hide furniture child templates in script")
	assert_false(room_shell_source.contains("rent_badge.position"), "Room rent badge position should be authored by anchors in RoomShell.tscn")
	assert_false(room_shell_scene.contains("RoomInfrastructure"), "Room shell should not keep old TextureRect infrastructure body")
	assert_false(room_shell_scene.contains("WallBase"), "Room shell should not keep old ColorRect wall body")
	assert_false(room_shell_scene.contains("FloorBase"), "Room shell should not keep old ColorRect floor body")
	assert_false(room_shell_scene.contains("RoofEaves"), "Room shell should not keep old TextureRect roof body")
	assert_false(floor_service_scene.contains("ServiceInfrastructure"), "Service core should not keep old TextureRect infrastructure body")
	assert_false(floor_service_scene.contains("DoorOrElevator"), "Service core should not keep old TextureRect door/elevator body")
	assert_false(floor_service_scene.contains("ServiceShade"), "Service core should not keep old ColorRect shade fallback")
	assert_true(room_source.contains("frame_tiles"), "Room rendering should read frame_tiles for grid-sized room upgrades")
	assert_true(room_source.contains("ApartmentTileMap.TILE_SIZE"), "Room pixel size should be derived from 16px TileMap cells")
	assert_true(room_source.contains("frame_tiles.y) * ApartmentTileMap.TILE_SIZE"), "Floor placement grid should use the full 4-tile room height")
	assert_true(room_source.contains("_wall_grid_rect"), "Room should expose a separate wall placement layer")
	assert_true(room_source.contains("world_position_to_placement_grid"), "Room should translate scene taps through furniture-aware placement layers")
	assert_true(room_source.contains("floor_grid_y_for"), "Floor furniture should map pointer input to the bottom floor line")
	assert_true(room_shell_source.contains("render_room_skeleton"), "RoomShell should delegate room-frame drawing to ApartmentTileMap")
	assert_true(room_source.contains("tenant_view.setup(tenant_id, room_id)"), "Room should bind tenant scene instances to their room")
	assert_true(room_source.contains("_furniture_position"), "Furniture should be positioned inside the room instead of listed as thumbnails")


func test_apartment_tilemap_renders_room_frame_tiles_on_16px_grid() -> void:
	var tilemap_script := ResourceLoader.load("res://scripts/building/ApartmentTileMap.gd", "Script", ResourceLoader.CACHE_MODE_IGNORE) as Script
	var scene := ResourceLoader.load("res://scenes/building/ApartmentTileMap.tscn", "PackedScene", ResourceLoader.CACHE_MODE_REPLACE) as PackedScene
	assert_true(scene != null, "ApartmentTileMap scene should load for direct preview")
	if scene == null:
		return
	var tilemap := scene.instantiate() as ApartmentTileMap
	assert_true(tilemap != null, "ApartmentTileMap scene should instantiate with its script")
	if tilemap == null:
		return
	assert_true(tilemap_script != null, "ApartmentTileMap test should reload the current script from disk")
	if tilemap_script != null:
		tilemap.set_script(tilemap_script)
	_bind_apartment_tilemap_layers(tilemap)
	var wallpaper_layer := tilemap.get_node("WallpaperTileMap") as TileMapLayer
	var wall_layer := tilemap.get_node("WallTileMap") as TileMapLayer
	var infrastructure_layer := tilemap.get_node("InfrastructureTileMap") as TileMapLayer

	tilemap.render_room_skeleton(Vector2i(6, 4), {}, false, false)
	assert_eq(tilemap.get("current_frame_tiles"), Vector2i(6, 4), "Initial room frame should be 6x4 tiles")
	assert_eq(tilemap.room_pixel_size(), Vector2(96, 64), "6x4 frame tiles should render as 96x64 pixels")
	assert_eq(wallpaper_layer.get_used_rect().position, Vector2i.ZERO, "Wallpaper should start at tile origin")
	assert_eq(wallpaper_layer.get_used_rect().size, Vector2i(6, 4), "Wallpaper layer should cover every room tile")
	assert_eq(wall_layer.get_used_rect().position, Vector2i.ZERO, "Room frame should start at tile origin")
	assert_eq(wall_layer.get_used_rect().size, Vector2i(6, 4), "Wall layer should occupy a 6x4 tile frame")
	assert_eq(infrastructure_layer.get_used_rect().position, Vector2i(-1, -1), "Infrastructure black wall edge should wrap one tile around the room frame")
	assert_eq(infrastructure_layer.get_used_rect().size, Vector2i(8, 6), "Infrastructure layer should include the outer black wall edge")
	assert_eq(infrastructure_layer.get_cell_source_id(Vector2i(0, 2)), -1, "ApartmentTileMap should not paint the old room door placeholder")
	var room_long_left_tiles: Array = tilemap.get("body_left_edge_tiles")
	var room_short_left_tiles: Array = tilemap.get("body_left_door_edge_tiles")
	var room_short_right_tiles: Array = tilemap.get("body_right_door_edge_tiles")
	assert_eq(wall_layer.get_cell_atlas_coords(Vector2i(0, 0)), tilemap.get("body_top_left_corner_tile"), "Room left wall with a door should start with the top-left corner")
	assert_eq(wall_layer.get_cell_atlas_coords(Vector2i(0, 1)), room_long_left_tiles[0], "Room left wall with a door should keep a long edge below the corner")
	assert_eq(wall_layer.get_cell_atlas_coords(Vector2i(0, 2)), room_short_left_tiles[0], "Room left wall with a door should use the short edge immediately above the door")
	var room_bottom_tiles: Array = tilemap.get("body_bottom_edge_tiles")
	assert_eq(wall_layer.get_cell_atlas_coords(Vector2i(0, 3)), room_bottom_tiles[0], "Room left wall with a door should use a bottom edge below the door")
	assert_eq(infrastructure_layer.get_cell_atlas_coords(Vector2i(5, 1)), Vector2i(5, 2), "Room window should use the configured right-wall tile")

	tilemap.render_room_skeleton(Vector2i(6, 4), {}, false, false, {"left": true, "right": false, "top": false, "bottom": false}, {}, "right")
	assert_eq(tilemap.get("current_door_side"), "right", "01 rooms should render a right-wall door cutout")
	assert_eq(tilemap.get("current_has_left_door"), false, "Right-wall-door rooms should not report a left door")
	assert_eq(tilemap.get("current_has_right_door"), true, "Right-wall-door rooms should report a right door")
	assert_eq(wall_layer.get_cell_atlas_coords(Vector2i(5, 0)), tilemap.get("body_top_right_corner_tile"), "Room right wall with a door should start with the top-right corner")
	assert_eq(wall_layer.get_cell_atlas_coords(Vector2i(5, 1)), tilemap.get("body_right_edge_tiles")[0], "Room right wall with a door should keep a long edge below the corner")
	assert_eq(wall_layer.get_cell_atlas_coords(Vector2i(5, 2)), room_short_right_tiles[0], "Right-wall door should use the right-side short door wall tile")
	assert_eq(wall_layer.get_cell_atlas_coords(Vector2i(5, 3)), room_bottom_tiles[0], "Right-wall door should use the bottom edge below the door")
	assert_eq(infrastructure_layer.get_cell_source_id(Vector2i(5, 1)), -1, "Right-wall doors should suppress the regular right-wall window")

	var left_edge_theme := {
		"edge_left_edge_tiles": [Vector2i(0, 3)],
		"edge_left_door_edge_tiles": [Vector2i(4, 1)]
	}
	tilemap.render_room_skeleton(Vector2i(3, 4), left_edge_theme, false, false, {"left": true, "right": false, "top": false, "bottom": false}, {"left": true, "right": false, "top": true, "bottom": true}, "left")
	assert_eq(infrastructure_layer.get_cell_atlas_coords(Vector2i(-1, 1)), Vector2i(0, 3), "Door service black edge should keep a long edge below the corner")
	assert_eq(infrastructure_layer.get_cell_atlas_coords(Vector2i(-1, 2)), Vector2i(4, 1), "Door service black edge should use edge_left_door_edge_tiles immediately above the door")

	tilemap.render_room_skeleton(Vector2i(3, 4), left_edge_theme, false, false, {"left": true, "right": false, "top": false, "bottom": false}, {"left": true, "right": false, "top": true, "bottom": true}, "")
	assert_eq(infrastructure_layer.get_cell_atlas_coords(Vector2i(-1, 2)), Vector2i(0, 3), "Closed service black edge should not use the door-short black edge tile")

	tilemap.render_room_skeleton(Vector2i(8, 4), {}, false, false)
	assert_eq(tilemap.get("current_frame_tiles"), Vector2i(8, 4), "Room expansion should only add width tiles")
	assert_eq(tilemap.room_pixel_size(), Vector2(128, 64), "8x4 frame tiles should render as 128x64 pixels")
	assert_eq(wallpaper_layer.get_used_rect().size, Vector2i(8, 4), "Expanded wallpaper layer should cover every room tile")
	assert_eq(wall_layer.get_used_rect().size, Vector2i(8, 4), "Expanded wall layer should keep fixed height")
	assert_eq(infrastructure_layer.get_used_rect().size, Vector2i(10, 6), "Expanded infrastructure layer should keep the one-tile outer wall edge")
	assert_eq(infrastructure_layer.get_cell_atlas_coords(Vector2i(7, 1)), Vector2i(5, 2), "Expanded room window should move with the right wall")

	tilemap.render_room_skeleton(Vector2i(3, 4), {}, false, false)
	assert_eq(tilemap.get("current_frame_tiles"), Vector2i(3, 4), "Service-core TileMaps should support 3-tile width")
	assert_eq(tilemap.room_pixel_size(), Vector2(48, 64), "3x4 service core should render as 48x64 pixels")
	assert_eq(wall_layer.get_used_rect().size, Vector2i(3, 4), "Service-core frame should not overpaint into the room")

	tilemap.render_room_skeleton(Vector2i(3, 4), {}, false, false, {"left": false, "right": false, "top": false, "bottom": false}, {"left": false, "right": false, "top": true, "bottom": true}, "")
	assert_eq(tilemap.get("current_body_sides").get("left", true), false, "Central elevator service should disable the left body side")
	assert_eq(tilemap.get("current_body_sides").get("right", true), false, "Service-core test should disable the right body side")
	assert_eq(tilemap.get("current_has_left_door"), false, "Central elevator service should render without a left exit-door cutout")
	assert_eq(tilemap.call("_body_side_enabled", "right"), false, "Service-core right body side helper should read the disabled side")
	var service_bottom_tiles: Array = tilemap.get("body_bottom_edge_tiles")
	assert_eq(tilemap.call("_body_tile_at", 2, 0, 2, 3), Vector2i(3, 17), "Open service top-right should resolve to the horizontal top edge tile")
	assert_eq(tilemap.call("_body_tile_at", 0, 3, 2, 3), service_bottom_tiles[0], "Open service bottom-left should resolve to the horizontal bottom edge tile")
	assert_eq(wall_layer.get_cell_source_id(Vector2i(0, 1)), -1, "Central service should not draw a left body wall next to the left room")
	assert_eq(wall_layer.get_cell_source_id(Vector2i(2, 1)), -1, "Central service should not draw a right body wall next to the right room")
	for x in range(3):
		assert_false(wall_layer.get_cell_source_id(Vector2i(x, 0)) == -1, "Service core should keep its top body edge")
		assert_false(wall_layer.get_cell_source_id(Vector2i(x, 3)) == -1, "Service core should keep its bottom body edge")
	var service_top_right_atlas: Vector2i = wall_layer.get_cell_atlas_coords(Vector2i(2, 0))
	var service_bottom_right_atlas: Vector2i = wall_layer.get_cell_atlas_coords(Vector2i(2, 3))
	assert_false(service_top_right_atlas == tilemap.get("body_top_right_corner_tile"), "Service top-right should use a top edge tile, not a removed right-corner tile: actual=%s corner=%s edges=%s" % [str(service_top_right_atlas), str(tilemap.get("body_top_right_corner_tile")), str(tilemap.get("body_top_edge_tiles"))])
	assert_false(service_bottom_right_atlas == tilemap.get("body_bottom_right_corner_tile"), "Service bottom-right should use a bottom edge tile, not a removed right-corner tile: actual=%s corner=%s edges=%s" % [str(service_bottom_right_atlas), str(tilemap.get("body_bottom_right_corner_tile")), str(tilemap.get("body_bottom_edge_tiles"))])
	assert_eq(wall_layer.get_cell_source_id(Vector2i(2, 1)), -1, "Service core should not draw a right body wall next to the room")
	assert_eq(infrastructure_layer.get_cell_source_id(Vector2i(2, 1)), -1, "Service core should not paint a right-wall window when the right wall is disabled")
	tilemap.free()


func test_room_layout_upgrades_are_config_driven_and_future_rooms_can_stay_hidden() -> void:
	var config_source := FileAccess.get_file_as_string("res://scripts/autoload/ConfigManager.gd")
	var state_source := FileAccess.get_file_as_string("res://scripts/autoload/GameState.gd")
	var floor_source := FileAccess.get_file_as_string("res://scripts/building/Floor.gd")
	var building_source := FileAccess.get_file_as_string("res://scripts/building/ApartmentBuilding.gd")
	for room in rooms:
		var room_data: Dictionary = room
		assert_true(room_data.has("room_scene_path"), "%s should expose room_scene_path for TileMap template selection" % room_data.get("id", ""))
		assert_true(room_data.has("layout_upgrades"), "%s should expose layout_upgrades for room expansion" % room_data.get("id", ""))
		assert_true(room_data.get("layout_upgrades", []).size() > 0, "%s should have at least one room layout upgrade template" % room_data.get("id", ""))
	assert_true(config_source.contains("get_room_layout_upgrade"), "ConfigManager should expose room layout upgrade lookup")
	assert_true(state_source.contains("apply_room_layout_upgrade"), "GameState should apply room layout upgrades without hardcoding sizes")
	assert_true(state_source.contains("unlock_room"), "GameState should expose a future room unlock path")
	assert_true(floor_source.contains("_room_is_visible"), "Floor rendering should hide future configured rooms until unlocked")
	assert_true(building_source.contains("_room_is_visible"), "Building sizing should hide future configured rooms until unlocked")
	for floor in floors:
		var floor_data: Dictionary = floor
		assert_true(floor_data.has("floor_scene_path"), "%dF should expose floor_scene_path for TileMap template selection" % int(floor_data.get("floor_index", 0)))
		assert_true(floor_data.has("build_slot_scene_path"), "%dF should expose build_slot_scene_path for construction template selection" % int(floor_data.get("floor_index", 0)))


func test_saved_room_layouts_are_normalized_to_current_config() -> void:
	var state_source := FileAccess.get_file_as_string("res://scripts/autoload/GameState.gd")
	var save_source := FileAccess.get_file_as_string("res://scripts/autoload/SaveManager.gd")
	assert_true(state_source.contains("_configured_room_layout_for_level"), "Saved room layout should be rebuilt from current config and room level")
	assert_true(state_source.contains("_fixed_height_frame_tiles"), "Room frame tile height should be fixed by GameState")
	assert_true(state_source.contains("_fixed_height_grid_size"), "Placement grid height should be fixed by GameState")
	assert_true(state_source.contains("SAVE_SCHEMA_VERSION"), "GameState should version saves before trusting persisted room layout levels")
	assert_true(state_source.contains("save_needs_writeback = false"), "Development-stage saves should not request legacy migration writeback by default")
	assert_true(save_source.contains("GameState.save_needs_writeback = false"), "SaveManager should clear writeback state after saving")
	assert_true(state_source.contains("\"frame_tiles\""), "Room saves should use frame_tiles instead of pixel dimensions")
	assert_true(state_source.contains("\"grid_size\""), "Room saves should use grid_size instead of pixel rectangles")
	assert_true(state_source.contains("\"layout_side\""), "Room saves should preserve left/right/suite layout side")
	assert_true(state_source.contains("\"door_side\""), "Room saves should preserve door-side routing")
	assert_true(state_source.contains("\"door_mirrored\""), "Room saves should preserve mirrored door state")
	assert_false(state_source.contains("\"room_size\""), "GameState should not preserve legacy pixel room_size fields")
	assert_false(state_source.contains("\"grid_rect\""), "GameState should not preserve legacy pixel grid_rect fields")
	assert_false(state_source.contains("[448, 176]"), "Old 720px-era room-size fallback should not survive in GameState")
	assert_false(state_source.contains("save_needs_writeback = saved_schema_version < SAVE_SCHEMA_VERSION"), "Development-stage saves should not branch into legacy layout migrations")
	assert_false(state_source.contains("if saved_schema_version < SAVE_SCHEMA_VERSION:"), "GameState should not keep old-save layout migration branches")
	assert_true(state_source.contains("configured_layout := _configured_room_layout_for_level"), "Current-version saves should rebuild frame/grid from config and room level")


func test_build_slots_match_apartment_floor_visual_structure() -> void:
	var building_source := FileAccess.get_file_as_string("res://scripts/building/ApartmentBuilding.gd")
	var slot_source := FileAccess.get_file_as_string("res://scripts/building/BuildSlot.gd")
	var building_scene := FileAccess.get_file_as_string("res://scenes/building/ApartmentBuilding.tscn")
	var slot_scene := FileAccess.get_file_as_string("res://scenes/building/BuildSlot.tscn")
	var slot_shell_scene := FileAccess.get_file_as_string("res://scenes/building/BuildSlotShell.tscn")
	var slot_shell_source := FileAccess.get_file_as_string("res://scripts/building/BuildSlotShell.gd")
	for floor in floors:
		var floor_data: Dictionary = floor
		assert_true(ResourceLoader.exists(str(floor_data.get("floor_scene_path", ""))), "%dF should configure a loadable floor scene template" % int(floor_data.get("floor_index", 0)))
		assert_true(ResourceLoader.exists(str(floor_data.get("build_slot_scene_path", ""))), "%dF should configure a loadable build-slot scene template" % int(floor_data.get("floor_index", 0)))
	assert_true(slot_scene.contains("BuildSlotShell.tscn"), "Build slots should compose the editable shell scene")
	assert_true(slot_scene.contains("StyleBoxFlat_slot_normal"), "Build slot button skin should be editor-authored")
	assert_true(slot_scene.contains("[node name=\"SceneConfig\" type=\"Node\""), "BuildSlot layout config should be authored in BuildSlot.tscn")
	assert_true(slot_scene.contains("[node name=\"TemplateText\" type=\"Control\""), "BuildSlot label templates should be authored in BuildSlot.tscn")
	assert_true(slot_scene.contains("[node name=\"LockedLabelTemplate\" type=\"Label\""), "Build slot locked label template should be authored in BuildSlot.tscn")
	assert_true(slot_scene.contains("[node name=\"BuildableLabelTemplate\" type=\"Label\""), "Build slot buildable label template should be authored in BuildSlot.tscn")
	assert_true(building_scene.contains("theme_override_constants/separation = 0"), "ApartmentBuilding spacing should be configured in the scene")
	assert_true(building_scene.contains("[node name=\"SceneConfig\" type=\"Node\""), "ApartmentBuilding should keep template config in ApartmentBuilding.tscn")
	assert_true(building_scene.contains("metadata/floor_scene_path = \"res://scenes/building/Floor.tscn\""), "ApartmentBuilding should assign the editable Floor template in scene metadata")
	assert_true(building_scene.contains("metadata/build_slot_scene_path = \"res://scenes/building/BuildSlot.tscn\""), "ApartmentBuilding should assign the editable BuildSlot template in scene metadata")
	assert_true(building_source.contains("floor_scene_path"), "ApartmentBuilding should allow floor config to select an editor-authored floor scene template")
	assert_true(building_source.contains("build_slot_scene_path"), "ApartmentBuilding should allow floor config to select an editor-authored build-slot template")
	assert_true(building_source.contains("_scene_from_path"), "ApartmentBuilding should load configured templates with scene default fallback")
	assert_true(slot_shell_scene.contains("BuildLeftRoomShell"), "Build slots should draw the left-side unbuilt room shell")
	assert_true(slot_shell_scene.contains("BuildServiceCore"), "Build slots should keep the central elevator service area")
	assert_true(slot_shell_scene.contains("BuildRightRoomShell"), "Build slots should draw the right-side unbuilt room shell")
	assert_true(slot_shell_scene.contains("name=\"BuildSlotShell\" type=\"HBoxContainer\""), "Build slot shell should lay out service and room areas in the editable scene")
	assert_true(slot_shell_source.contains("_room_edge_sides(\"left\")"), "Build-slot left room should render with left-side ownership")
	assert_true(slot_shell_source.contains("_room_edge_sides(\"right\")"), "Build-slot right room should render with right-side ownership")
	assert_true(slot_shell_scene.contains("ApartmentTileMap.tscn"), "Build slots should reuse the editable apartment TileMap template")
	assert_true(slot_shell_scene.contains("ServiceCoreTileMap.tscn"), "Build slots should reuse the editable service-core TileMap template")
	assert_true(slot_shell_scene.contains("ConstructionCover"), "Build slots should keep the construction cloth as a scene-authored texture overlay")
	assert_true(slot_shell_scene.contains("AtlasTexture_construction_cover"), "Build slot construction cover should use a scene-authored AtlasTexture")
	assert_true(slot_shell_scene.contains("theme_override_font_sizes/font_size = 9"), "Build slot label style should be editor-authored")
	assert_true(slot_shell_scene.contains("text = \"待修建\""), "Build slot label should be previewable in BuildSlotShell.tscn")
	assert_false(slot_shell_scene.contains("BuildRoomInfrastructure"), "Build slots should not keep old TextureRect infrastructure body")
	assert_false(slot_shell_scene.contains("BuildServiceInfrastructure"), "Build slots should not keep old TextureRect service infrastructure body")
	assert_false(slot_shell_scene.contains("BuildDoorOrElevator"), "Build slots should not keep old TextureRect door/elevator body")
	assert_false(slot_shell_scene.contains("ConstructionCloth"), "Build slots should not keep old TextureRect construction cloth")
	assert_false(slot_shell_scene.contains("TrafficCone"), "Build slots should not keep old TextureRect traffic cones")
	assert_false(slot_shell_scene.contains("BuildRoofEaves"), "Build slots should not keep old TextureRect roof")
	assert_false(slot_shell_scene.contains("BuildSlotScrim"), "Build slots should not keep old ColorRect construction fallback")
	assert_false(slot_shell_source.contains("room_shell.position"), "BuildSlotShell should not hand-position room shells at runtime")
	assert_false(slot_source.contains("@export var construction_cloth_texture"), "Construction cover should stay scene-authored instead of exported from script")
	assert_false(slot_source.contains("@export var roof_texture"), "Build-slot roof should move to the editor-painted TileMap")
	assert_false(slot_source.contains("apply_asset_to_texture_rect"), "BuildSlot should not patch building visuals from scripts")
	assert_false(slot_source.contains("AtlasTexture.new"), "BuildSlot should not create atlas slices for building visuals")
	assert_false(slot_shell_source.contains("service_core.position"), "BuildSlotShell should not hand-position the service core at runtime")
	assert_false(slot_source.contains("StyleBoxFlat.new"), "BuildSlot should not create fixed button skins in script")
	assert_false(slot_source.contains("add_theme_"), "BuildSlot should not hide fixed label styling in script")
	assert_false(slot_source.contains("@export"), "BuildSlot should read scene-authored config instead of script exports")
	assert_false(slot_source.contains("_asset_tile_origin"), "BuildSlot should not infer TileSet atlas coordinates from room asset regions")
	assert_false(slot_source.contains("wallpaper_origin"), "BuildSlot should not pass guessed wallpaper atlas origins")
	assert_false(slot_source.contains("frame_origin"), "BuildSlot should not pass guessed frame atlas origins")
	assert_false(slot_source.contains("待修建"), "BuildSlot should not hard-code build-state copy in script")
	assert_false(slot_source.contains("金币"), "BuildSlot should not hard-code build-cost copy in script")
	assert_false(slot_source.contains("解锁"), "BuildSlot should not hard-code locked-state copy in script")
	assert_false(slot_source.contains("UIPanelFactory.style_button"), "Build slots should not look like a menu button")
	assert_false(building_source.contains("preload(\"res://scenes/building/Floor.tscn\")"), "ApartmentBuilding should not hide floor templates in script")
	assert_false(building_source.contains("preload(\"res://scenes/building/BuildSlot.tscn\")"), "ApartmentBuilding should not hide build-slot templates in script")
	assert_false(building_source.contains("@export"), "ApartmentBuilding should read scene-authored config instead of script exports")
	assert_true(building_source.contains("_has_visible_next_build_slot"), "Top built room should not duplicate roof/eaves below a visible build slot")
	assert_true(building_source.contains("_floor_size"), "Build slots should reserve configurable floor heights")
