@tool
extends "res://tests/support/TestSuiteBase.gd"

func suite_name() -> String:
	return "tenant_ai"

func test_tenant_uses_character_body_click_area_and_strict_animations() -> void:
	var tenant_scene := FileAccess.get_file_as_string("res://scenes/tenant/Tenant.tscn")
	var tenant_source := FileAccess.get_file_as_string("res://scripts/tenant/Tenant.gd")
	var room_source := FileAccess.get_file_as_string("res://scripts/building/Room.gd")
	var main_source := FileAccess.get_file_as_string("res://scenes/main/Main.gd")
	var locator_source := FileAccess.get_file_as_string("res://scripts/tenant/TenantRoomLocator.gd")
	var ai_source := FileAccess.get_file_as_string("res://scripts/tenant/TenantAI.gd")
	var need_bubble_scene := FileAccess.get_file_as_string("res://scenes/tenant/NeedBubble.tscn")
	var need_bubble_source := FileAccess.get_file_as_string("res://scripts/tenant/NeedBubble.gd")
	var emote_scene := FileAccess.get_file_as_string("res://scenes/tenant/TenantEmote.tscn")
	var emote_source := FileAccess.get_file_as_string("res://scripts/tenant/TenantEmote.gd")
	assert_true(tenant_scene.contains("[node name=\"Tenant\" type=\"CharacterBody2D\""), "Tenant should be a map CharacterBody2D scene")
	assert_true(tenant_scene.contains("AnimatedSprite2D"), "Tenant should reserve AnimatedSprite2D for future spritesheets")
	assert_true(tenant_scene.contains("NeedBubble.tscn"), "Tenant should instance the reusable NeedBubble scene")
	assert_true(tenant_scene.contains("TenantAI.gd"), "Tenant should own a per-instance AI state machine")
	assert_true(tenant_scene.contains("[node name=\"TenantAI\" type=\"Node\""), "TenantAI should be a scene child, not a global Main loop")
	assert_true(tenant_scene.contains("[node name=\"ClickArea\" type=\"Area2D\""), "Tenant clicks should be routed through a scene-authored ClickArea")
	assert_true(tenant_scene.contains("[node name=\"ClickShape\" type=\"CollisionShape2D\""), "Tenant ClickArea should expose its hit shape in the scene")
	assert_true(tenant_scene.contains("position = Vector2(28, 56)"), "Tenant standalone preview should place the character inside the viewport")
	assert_true(tenant_scene.contains("position = Vector2(0, -7)"), "Tenant avatar should compensate for transparent padding in the unscaled 32x32 NPC frame")
	assert_true(tenant_scene.contains("region = Rect2(0, 32, 32, 32)"), "Tenant atlas frames should match the configured 32x32 Pixel Spaces NPC grid")
	assert_false(tenant_scene.contains("region = Rect2(0, 32, 16, 32)"), "Tenant atlas frames should not override the configured 32x32 NPC grid")
	assert_false(tenant_scene.contains("scale = Vector2(1.5, 1.5)"), "Tenant should render the configured 32x32 NPC frames at scene scale")
	assert_true(tenant_scene.contains("sprite_frames = SubResource"), "Tenant avatar frames should be prebuilt on AvatarSprite in Tenant.tscn")
	assert_true(tenant_scene.contains("\"name\": &\"walk\""), "Tenant.tscn should prebuild a walk animation on AvatarSprite")
	assert_true(tenant_scene.contains("BehaviorAnimationMap"), "Tenant behavior-to-animation bindings should be authored in Tenant.tscn")
	assert_true(tenant_scene.contains("metadata/default_avatar_animation = \"idle\""), "Tenant default avatar animation should be scene metadata")
	assert_true(tenant_scene.contains("metadata/avatar_animation = \"walk\""), "Tenant walk animation binding should be scene metadata")
	assert_false(tenant_scene.contains("metadata/moves = true"), "Tenant movement should live in TenantAI, not animation metadata")
	assert_false(tenant_scene.contains("metadata/behavior_keys = \"wander,recruited,entertainment,eat,clean,study,relax\""), "Only common visible actions should bind to avatar animations")
	assert_true(need_bubble_scene.contains("[node name=\"NeedBubble\" type=\"Control\""), "NeedBubble should be a previewable Control scene")
	assert_true(need_bubble_scene.contains("BubbleAnimation\" type=\"AnimatedSprite2D\""), "NeedBubble should reserve an AnimatedSprite2D bubble node")
	assert_true(need_bubble_scene.contains("IconRoot"), "NeedBubble should expose an icon root in the scene")
	assert_true(need_bubble_scene.contains("SleepIcon"), "NeedBubble should expose behavior icon nodes in the scene")
	assert_true(need_bubble_scene.contains("metadata/behavior_key = \"sleep\""), "NeedBubble behavior icons should be bound through scene metadata")
	assert_true(need_bubble_scene.contains("metadata/behavior_keys = \"relax,happy\""), "NeedBubble shared icons should be bound through scene metadata")
	assert_true(need_bubble_scene.contains("\"loop\": false"), "NeedBubble animation should be non-looping so icons can appear after it finishes")
	assert_true(emote_scene.contains("[node name=\"TenantEmote\" type=\"Control\"]"), "TenantEmote should be a previewable Control scene")
	assert_true(emote_scene.contains("EmoteAnimation\" type=\"AnimatedSprite2D\""), "TenantEmote should reserve an AnimatedSprite2D emote node")
	assert_true(emote_scene.contains("IconRoot"), "TenantEmote should expose an icon root in the scene")
	assert_true(emote_scene.contains("HappyIcon"), "TenantEmote should expose emote icon nodes in the scene")
	assert_true(emote_scene.contains("metadata/emote_key = \"happy\""), "TenantEmote icons should be bound through scene metadata")
	assert_true(emote_scene.contains("\"loop\": false"), "TenantEmote animation should be non-looping so icons can appear after it finishes")
	assert_true(tenant_source.contains("need_bubble.show_behavior"), "Tenant behavior bubble should be delegated to NeedBubble")
	assert_true(tenant_source.contains("UIManager.open_tenant_panel"), "Clicking an in-room tenant should open tenant context")
	assert_true(tenant_source.contains("_play_avatar_animation"), "Tenant should actively play the behavior animation")
	assert_true(tenant_source.contains("GameEvents.tenant_behavior_changed.connect"), "Tenant animation should refresh on ordinary AI behavior changes")
	assert_true(tenant_source.contains("TenantAI"), "Tenant should bind its scene-authored AI node")
	assert_true(tenant_source.contains("ClickArea"), "Tenant should bind the scene-authored click area")
	assert_true(tenant_source.contains("push_error(\"Tenant AvatarSprite is missing animation"), "Missing tenant animations should be explicit errors")
	assert_true(ai_source.contains("enum AIState"), "TenantAI should use an explicit state machine")
	assert_true(ai_source.contains("AIState.IDLE"), "TenantAI should support idle")
	assert_true(ai_source.contains("AIState.WALK"), "TenantAI should support walking")
	assert_true(ai_source.contains("AIState.JUMP"), "TenantAI should support jumping")
	assert_true(ai_source.contains("AIState.BUBBLE_ACTION"), "TenantAI should support bubble-only actions")
	assert_true(ai_source.contains("AIState.ENTERING"), "TenantAI should support startup entry routes from offscreen")
	assert_true(ai_source.contains("AIState.LEAVING"), "TenantAI should support leaving routes")
	assert_true(ai_source.contains("AIState.AWAY"), "TenantAI should support hidden away state")
	assert_true(ai_source.contains("AIState.RETURNING"), "TenantAI should support returning routes")
	assert_true(ai_source.contains("_sync_from_current_behavior"), "TenantAI setup should restore current state without overwriting observed behavior")
	assert_true(ai_source.contains("startup_entry_tenant_ids"), "TenantAI should only play the startup entry route once per tenant per game session")
	assert_true(ai_source.contains("startup_entry_active_tenant_ids"), "TenantAI should expose active startup entry tenants to prevent duplicate room/world views")
	assert_true(ai_source.contains("startup_entry_refresh_active"), "TenantAI should only start offscreen entry during the loaded-state startup refresh")
	assert_true(ai_source.contains("static func reset_startup_entry_session"), "TenantAI should reset startup entry tracking for each BuildingView scene session")
	assert_true(ai_source.contains("static func begin_startup_entry_refresh"), "TenantAI should expose an explicit startup-entry refresh window")
	assert_true(ai_source.contains("static func end_startup_entry_refresh"), "TenantAI should close the startup-entry refresh window after the initial scene build")
	assert_true(ai_source.contains("static func is_startup_entry_active"), "TenantAI should let room rendering detect startup route tenants")
	assert_true(ai_source.contains("_mark_startup_entry_finished"), "TenantAI should clear the startup entry active flag when the route ends")
	assert_true(ai_source.contains("_run_startup_entry_route"), "TenantAI should own the startup route from the left offscreen mark")
	assert_true(ai_source.contains("_run_leaving_route"), "TenantAI should own the deterministic leaving route")
	assert_true(ai_source.contains("_run_returning_route"), "TenantAI should own the deterministic returning route")
	assert_true(ai_source.contains("_run_entry_route(false, true)"), "Startup entry should reuse the home route without changing persisted presence")
	assert_true(ai_source.contains("GameState.set_tenant_presence"), "TenantAI routes should sync persisted presence state")
	assert_true(ai_source.contains("get_tenant_world_layer"), "TenantAI should promote route movement to the building tenant layer")
	assert_true(ai_source.contains("get_offscreen_left_world_position"), "TenantAI should start and finish external routes at the shared offscreen mark")
	assert_true(ai_source.contains("TenantRoomLocator.spawn_position"), "TenantAI should spawn from the room floor grid")
	assert_true(room_source.contains("TenantAI.is_startup_entry_active"), "Room should not create a duplicate in-room tenant while startup entry is active")
	assert_true(room_source.contains("tenant_view.visible = false"), "Room should hide tenant instances before adding them to the scene so preview coordinates never flash")
	assert_true(room_source.contains("visual_layer.add_child(tenant_view)\n\ttenant_view.setup(tenant_id, room_id)"), "Room should add tenant views before setup so TenantAI can resolve BuildingView and start offscreen entry")
	assert_true(ai_source.contains("TenantRoomLocator.walk_positions"), "TenantAI should patrol using room floor grid positions")
	assert_true(ai_source.contains("TenantRoomLocator.interaction_position"), "TenantAI should use grid-based furniture interaction points")
	assert_true(locator_source.contains("class_name TenantRoomLocator"), "Tenant room positions should live in a dedicated grid locator")
	assert_true(locator_source.contains("FurniturePlacementRules.door_cells_for_layer"), "Tenant grid positions should avoid floor door cells")
	assert_true(need_bubble_source.contains("await bubble_animation.animation_finished"), "NeedBubble should reveal icons only after the bubble animation finishes")
	assert_true(emote_source.contains("await emote_animation.animation_finished"), "TenantEmote should reveal icons only after the emote animation finishes")
	assert_false(tenant_scene.contains("behavior_animation_map = {"), "Tenant.tscn should not keep script-exported behavior animation config")
	assert_false(tenant_scene.contains("ColorFallback"), "Tenant should not keep a color fallback visual")
	assert_false(tenant_source.contains("BEHAVIOR_ANIMATION"), "Tenant behavior animation bindings should stay in Tenant.tscn metadata")
	assert_false(tenant_source.contains("@export"), "Tenant should not expose avatar frame or animation config in script")
	assert_false(tenant_source.contains("AssetResolver"), "Tenant should not rebuild AvatarSprite frames from data at runtime")
	assert_false(tenant_source.contains("_avatar_asset_from_config"), "Tenant should rely on scene-authored AvatarSprite frames")
	assert_false(tenant_source.contains("_frame_entries"), "Tenant should not generate animation frame entries in script")
	assert_false(tenant_source.contains("@export var avatar_scale"), "Tenant fixed avatar scale should stay in Tenant.tscn")
	assert_false(tenant_source.contains("set_avatar_scale"), "Rooms should not tune tenant visual layout at runtime")
	assert_false(tenant_source.contains("custom_minimum_size ="), "Tenant fixed size should stay in Tenant.tscn")
	assert_false(tenant_source.contains("mouse_filter ="), "Tenant mouse filtering should stay in Tenant.tscn")
	assert_false(tenant_source.contains("focus_mode ="), "Tenant focus mode should stay in Tenant.tscn")
	assert_false(tenant_source.contains("need_bubble.position"), "NeedBubble placement should stay in NeedBubble.tscn")
	assert_false(tenant_source.contains("fallback_animation"), "Tenant should not fall back to another avatar animation")
	assert_false(tenant_source.contains("color_fallback"), "Tenant should not toggle fallback visuals")
	assert_false(tenant_source.contains("accept_event()"), "Tenant should not use Control GUI event handling")
	assert_false(tenant_source.contains("Rect2(Vector2.ZERO, size)"), "Tenant click checks should not depend on Control size")
	assert_false(tenant_source.contains("func _gui_input"), "Tenant root should not use Control _gui_input")
	assert_false(tenant_source.contains("position = base_position"), "Tenant should not snap back to its spawn point every frame")
	assert_false(tenant_source.contains("current_behavior_moves"), "Tenant should not own behavior movement state")
	assert_false(tenant_source.contains("睡觉"), "Tenant behavior labels should not be hard-coded in script")
	assert_false(need_bubble_scene.contains("bubble_text_by_behavior = {"), "NeedBubble should use scene-authored icon nodes instead of exported text dictionaries")
	assert_false(need_bubble_source.contains("@export"), "NeedBubble should not require script-level exported bubble text configuration")
	assert_false(need_bubble_source.contains("BEHAVIOR_ICON_NODE"), "NeedBubble behavior icon bindings should stay in scene metadata")
	assert_false(need_bubble_source.contains("BUBBLE_ANIMATION"), "NeedBubble animation selection should stay on the AnimatedSprite2D node")
	assert_false(need_bubble_source.contains("get_animation_names"), "NeedBubble should not choose a fallback animation")
	assert_false(need_bubble_source.contains("睡觉"), "NeedBubble should not keep display behavior names in script")
	assert_false(need_bubble_source.contains("学习/工作"), "NeedBubble display text should stay in NeedBubble.tscn")
	assert_false(emote_scene.contains("[node name=\"TenantEmote\" type=\"Label\"]"), "TenantEmote should not be a text-only label scene")
	assert_false(emote_source.contains("extends Label"), "TenantEmote should not render text directly")
	assert_false(emote_source.contains("@export"), "TenantEmote should not require script-level exported visual configuration")
	assert_false(emote_source.contains("EMOTE_ICON_NODE"), "TenantEmote icon bindings should stay in scene metadata")
	assert_false(emote_source.contains("EMOTE_ANIMATION"), "TenantEmote animation selection should stay on the AnimatedSprite2D node")
	assert_false(emote_source.contains("get_animation_names"), "TenantEmote should not choose a fallback animation")
	assert_false(room_source.contains("set_avatar_scale"), "Room should only position tenant scenes, not rewrite their internal visual layout")
	assert_false(room_source.contains("tenant_offset"), "Room should not keep naked tenant spawn coordinates")
	assert_false(room_source.contains("Marker2D"), "Room should not use scene anchors for tenant AI positions")
	assert_false(room_source.contains("tenant_view.position ="), "Room should not own tenant positioning beyond instantiation")
	assert_false(room_source.contains("func _tenant_position"), "Room should not own tenant positioning beyond instantiation")
	assert_false(room_source.contains("clampf(tenant_offset"), "Room should not clamp tenant movement against room bounds")
	assert_false(room_source.contains("room_pixel_size.y - 48.0"), "Room should not clamp CharacterBody2D tenants as if they were top-left Control previews")
	assert_false(room_source.contains("room_pixel_size.y - 4.0"), "Room should not leave CharacterBody2D tenants hovering above the floor")
	assert_false(main_source.contains("tenant_ai_timer"), "Main should not run global tenant AI ticks")
	assert_false(main_source.contains("_tick_tenant_ai"), "Main should not own tenant AI behavior selection")
	assert_false(main_source.contains("func _ready() -> void:\n\t_connect_events()\n\t_refresh_all()"), "Main should wait for state_loaded before the first building refresh so startup entry tenants are not rebuilt")
	assert_true(main_source.contains("state_loaded_once"), "Main should gate building refresh events until save loading finishes")
	assert_true(main_source.contains("GameEvents.state_loaded.connect(_on_state_loaded)"), "Main should route loaded-state refresh through a startup-entry reset")
	assert_true(main_source.contains("func _on_state_loaded()"), "Main should own loaded-state startup refresh")
	assert_true(main_source.contains("TenantAI.begin_startup_entry_refresh()\n\tstate_loaded_once = true\n\t_refresh_all()\n\tTenantAI.end_startup_entry_refresh()"), "Main should open startup-entry routing only around the first real refresh")
	assert_true(main_source.contains("func _refresh_building_if_loaded()"), "Main should ignore building rebuild events emitted during save normalization")
	assert_false(main_source.contains("_on_rent_changed(_value: float) -> void:\n\t_refresh_top_bar()\n\t_refresh_building()"), "Rent changes should not rebuild rooms and reset TenantAI state")
	assert_false(need_bubble_source.contains("mouse_filter ="), "NeedBubble fixed interaction settings should stay in NeedBubble.tscn")
	assert_false(emote_source.contains("mouse_filter ="), "TenantEmote fixed interaction settings should stay in TenantEmote.tscn")


func test_tenant_room_locator_uses_floor_grid_positions() -> void:
	var locator_source := FileAccess.get_file_as_string("res://scripts/tenant/TenantRoomLocator.gd")
	var room := {
		"id": "__tenant_locator_test",
		"frame_tiles": [8, 4],
		"grid_size": [6, 4],
		"furniture_instances": []
	}
	assert_true(locator_source.contains("static func floor_grid_y"), "TenantRoomLocator should expose floor row calculation")
	assert_true(locator_source.contains("static func spawn_position"), "TenantRoomLocator should expose spawn position generation")
	assert_true(locator_source.contains("static func walk_positions"), "TenantRoomLocator should expose patrol position generation")
	assert_true(locator_source.contains("static func interaction_position"), "TenantRoomLocator should expose furniture interaction position generation")
	assert_true(locator_source.contains("static func room_door_inside_grid"), "TenantRoomLocator should expose the room-door route grid")
	assert_true(locator_source.contains("static func room_door_inside_position"), "TenantRoomLocator should expose the room-door route position")
	var floor_row: int = FurniturePlacementRules.floor_grid_y_for(room["grid_size"], [1, 1])
	var door_cells: Array = FurniturePlacementRules.door_cells_for_layer(room, FurniturePlacementRules.LAYER_FLOOR)
	var standing_grids: Array = []
	for x in range(int(room["grid_size"][0])):
		var cell: Array = [x, floor_row]
		if not door_cells.has(cell):
			standing_grids.append(cell)
	var tile_size: int = int(FurniturePlacementRules.TILE_SIZE)
	var floor_origin: Vector2 = Vector2(float(tile_size), 0.0)
	var door_route_grid: Array = door_cells.front()
	var door_route_position: Vector2 = floor_origin + Vector2(0.5 * tile_size, 4.0 * tile_size)
	assert_eq(floor_row, 3, "Tenant floor row should be the bottom floor grid row")
	assert_eq(standing_grids, [[1, 3], [2, 3], [3, 3], [4, 3], [5, 3]], "Tenant standing grids should avoid the floor door cell")
	assert_eq(door_route_grid, [0, 3], "Tenant door route should target the reserved left-bottom door cell")
	assert_eq(door_route_position, Vector2(24.0, 64.0), "Tenant door route should walk to the inside of the left-bottom room door")
	assert_eq(standing_grids[3], [4, 3], "Tenant spawn should default to a middle-right floor cell")
	assert_eq(floor_origin + Vector2(4.5 * tile_size, 4.0 * tile_size), Vector2(88.0, 64.0), "Tenant spawn foot point should sit on the room floor")
	assert_eq([standing_grids.front(), standing_grids.back()], [[1, 3], [5, 3]], "Tenant walk range should avoid the floor door cell")

	room["furniture_instances"] = [
		{"instance_id": "bed_a", "furniture_id": "bed_basic", "grid_pos": [1, 2]}
	]
	var bed_data := _furniture_data("bed_basic")
	var bed_size: Array = bed_data.get("size", [])
	var interaction_grid := [int(room["furniture_instances"][0]["grid_pos"][0]) + int(bed_size[0]), floor_row]
	assert_eq(interaction_grid, [3, 3], "Tenant interaction point should stand beside floor furniture")
	assert_eq(floor_origin + Vector2(3.5 * tile_size, 4.0 * tile_size), Vector2(72.0, 64.0), "Tenant interaction foot point should remain on the floor")


func test_tenant_presence_state_is_saved_and_normalized() -> void:
	var game_state_source := FileAccess.get_file_as_string("res://scripts/autoload/GameState.gd")
	var events_source := FileAccess.get_file_as_string("res://scripts/autoload/GameEvents.gd")
	var config_source := FileAccess.get_file_as_string("res://scripts/autoload/ConfigManager.gd")
	assert_true(game_state_source.contains("TENANT_PRESENCE_HOME := \"home\""), "GameState should define a home presence state")
	assert_true(game_state_source.contains("TENANT_PRESENCE_LEAVING := \"leaving\""), "GameState should define a leaving presence state")
	assert_true(game_state_source.contains("TENANT_PRESENCE_AWAY := \"away\""), "GameState should define an away presence state")
	assert_true(game_state_source.contains("TENANT_PRESENCE_RETURNING := \"returning\""), "GameState should define a returning presence state")
	assert_true(game_state_source.contains("\"presence_state\": TENANT_PRESENCE_HOME"), "New tenant saves should default to home presence")
	assert_true(game_state_source.contains("\"away_until_timestamp\": 0"), "New tenant saves should default away timestamp")
	assert_true(game_state_source.contains("\"presence_target_room_id\": \"\""), "New tenant saves should reserve target room routing")
	assert_true(game_state_source.contains("func set_tenant_presence"), "GameState should expose presence syncing")
	assert_true(game_state_source.contains("save_needs_writeback = true"), "Presence changes should mark saves dirty")
	assert_true(events_source.contains("signal tenant_presence_changed"), "Presence changes should emit a dedicated event")
	assert_true(config_source.contains("func get_tenant_ai_value"), "Tenant AI tuning should be read from economy config")
	assert_true(economy.has("tenant_ai"), "Economy config should include tenant AI tuning")
	var ai_config: Dictionary = economy.get("tenant_ai", {})
	assert_true(ai_config.has("away_chance"), "Tenant AI config should include away chance")
	assert_true(ai_config.has("away_seconds"), "Tenant AI config should include away duration")
	assert_true(ai_config.has("route_speed"), "Tenant AI config should include route speed")
	assert_true(ai_config.has("entry_from_offscreen"), "Tenant AI config should include startup entry route toggling")
	assert_true(ai_config.has("door_animation_seconds"), "Tenant AI config should include door animation wait")
	assert_true(ai_config.has("elevator_animation_seconds"), "Tenant AI config should include elevator animation wait")
	assert_true(ai_config.has("offscreen_margin"), "Tenant AI config should include offscreen route margin")
	assert_eq(float(ai_config.get("offscreen_margin", 0.0)), 64.0, "Tenant offscreen route mark should sit well outside the visible left edge")
	assert_true(game_state_source.contains("\"tenants\": tenants"), "Tenant presence fields should be included in save data")
	assert_true(game_state_source.contains("_ensure_runtime_defaults()"), "Loaded saves should normalize tenant presence fields")
	assert_true(game_state_source.contains("TENANT_PRESENCE_AWAY and int(tenant[\"away_until_timestamp\"]) <= TimeManager.now_unix()"), "Expired away presence should resume as returning")
	assert_true(game_state_source.contains("tenant[\"presence_state\"] = TENANT_PRESENCE_RETURNING"), "Leaving or expired away presence should normalize into returning")
	assert_true(game_state_source.contains("if presence == TENANT_PRESENCE_HOME:"), "Home presence should clear route-only fields")
	assert_true(game_state_source.contains("tenant[\"away_until_timestamp\"] = 0"), "Home or unassigned tenants should clear away timestamp")
	assert_true(game_state_source.contains("tenant[\"presence_target_room_id\"] = \"\""), "Home or unassigned tenants should clear target room")


func test_tenant_behavior_state_uses_keys_with_alias_config() -> void:
	var game_state_source := FileAccess.get_file_as_string("res://scripts/autoload/GameState.gd")
	var main_source := FileAccess.get_file_as_string("res://scenes/main/Main.gd")
	var config_source := FileAccess.get_file_as_string("res://scripts/autoload/ConfigManager.gd")
	var alias_config := FileAccess.get_file_as_string("res://data/behavior_aliases.json")
	assert_true(config_source.contains("behavior_aliases"), "ConfigManager should load behavior aliases for old save compatibility")
	assert_true(alias_config.contains("\"睡觉\": \"sleep\""), "Behavior aliases should migrate old display labels to behavior keys")
	assert_true(game_state_source.contains("DEFAULT_TENANT_BEHAVIOR := \"wander\""), "GameState should store behavior keys, not display labels")
	assert_true(game_state_source.contains("_need_to_behavior_key"), "Need updates should resolve to behavior keys")
	assert_true(game_state_source.contains("func set_tenant_behavior"), "GameState should expose ordinary tenant behavior syncing for TenantAI")
	assert_true(game_state_source.contains("tenant_behavior_changed.emit"), "Ordinary behavior changes should emit a visual refresh signal")
	assert_false(main_source.contains("GameState.IDLE_TENANT_BEHAVIOR"), "Main should not choose tenant behavior keys after TenantAI owns behavior selection")
	assert_false(game_state_source.contains("\"闲逛\""), "GameState should not hard-code display behavior labels")
	assert_false(game_state_source.contains("\"入住\""), "GameState should not hard-code recruited display labels")
	assert_false(main_source.contains("\"发呆\""), "Main should not write display behavior labels into state")
